#!/usr/bin/env bash

## Files and cmd
FILE="$HOME/.cache/launch_main.eww"
CONFIG="$HOME/.config/eww/structs/main-utils"

run_eww() {
  eww -c "$CONFIG" open-many "background"    	\
			     "time" 	                          \
			     "user"		                          \
		  	   "system" 		                      \
			     "uptime"        	                  \
			     "directories"   	                  \
			     "wshutdown"     	                  \
	         "wreboot"       	                  \
			     "wlogout"       	                  \
			     "wlock"	     	                    \
			     "wsuspend"      	                  \
			     "audio"		                          \
			     "quicklinks"	                      \
			     "audiocontrol"
}

close_eww() {
  eww -c "$CONFIG" close "background"     \
	    		 "time" 	                      \
	    		 "user"			                    \
	    	   "system" 	                    \
	    		 "uptime"            	          \
	    		 "directories"       	          \
	    		 "wshutdown"         	          \
	    		 "wreboot"           	          \
	    		 "wlogout"           	          \
	    		 "wlock"	     	                \
	    		 "wsuspend"       	            \
	    		 "audio"			                    \
	    		 "quicklinks"		                \
	    		 "audiocontrol"
}

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
  run_eww
  touch "$FILE"
else
  close_eww
  rm "$FILE"
fi

# vim:ft=bash:nowrap
