# AppImageLauncher
# Autogenerated from man page /usr/share/man/man1/AppImageLauncher.1.gz
complete -c AppImageLauncher -l appimagelauncher-help -d 'Display this help and exit'
complete -c AppImageLauncher -l appimagelauncher-version -d 'Display version and exit ARGUMENTS Path to AppImage (mandatory)'

