# card
# Autogenerated from man page /usr/share/man/man1/card.1.gz
complete -c card -s h -l help -d 'display this help and exit'
complete -c card -s v -l version -d 'display version information and exit'
complete -c card -s o -l output -d 'save the output in FILE'
complete -c card -s l -l language -d 'print the help in the language LL (default: English)'
complete -c card -l command -d 'perform pretty-printing on the output of CMD (e. g'

