# curlftpfs
# Autogenerated from man page /usr/share/man/man1/curlftpfs.1.gz
complete -c curlftpfs -o h/--help -d 'Print help options'
complete -c curlftpfs -o v/--verbose -d 'Make libcurl print verbose debug output'
complete -c curlftpfs -o V/--version -d 'Print curlftpfs, libcurl and fuse versions'
complete -c curlftpfs -s o -d 'Options are specified with a'
complete -c curlftpfs -s d -d option
complete -c curlftpfs -s f -d 'Run curlftpfs in foreground mode'
complete -c curlftpfs -s r -d 'Mount read-only'
complete -c curlftpfs -s s -d 'Disable multi-threaded operation'

