# dbiprof.1p
# Autogenerated from man page /usr/share/man/man1/dbiprof.1p.gz
complete -c 'dbiprof.1p' -l number -d 'X Item "--number N" Produce this many items in the report.   Defaults to 10'
complete -c 'dbiprof.1p' -l sort -d 'X Item "--sort field" Sort results by the given field'
complete -c 'dbiprof.1p' -l reverse -d 'X Item "--reverse" Reverses the selected sort'
complete -c 'dbiprof.1p' -l match -d 'X Item "--match keyN=value" Consider only items where the specified key match…'
complete -c 'dbiprof.1p' -l exclude -d 'X Item "--exclude keyN=value" Remove items for where the specified key matche…'
complete -c 'dbiprof.1p' -l case-sensitive -d 'X Item "--case-sensitive" Using this option causes --match and --exclude to w…'
complete -c 'dbiprof.1p' -l delete -d 'X Item "--delete" Sets the \\f(CW\\*(C`DeleteFiles\\*(C\' option to DBI::ProfileD…'
complete -c 'dbiprof.1p' -l dumpnodes -d 'X Item "--dumpnodes" Print the list of nodes in the form of a perl data struc…'
complete -c 'dbiprof.1p' -l version

