# dbiproxy.1p
# Autogenerated from man page /usr/share/man/man1/dbiproxy.1p.gz
complete -c 'dbiproxy.1p' -l chroot
complete -c 'dbiproxy.1p' -l user
complete -c 'dbiproxy.1p' -l configfile
complete -c 'dbiproxy.1p' -l debug
complete -c 'dbiproxy.1p' -l facility
complete -c 'dbiproxy.1p' -l group
complete -c 'dbiproxy.1p' -l localaddr
complete -c 'dbiproxy.1p' -l localport
complete -c 'dbiproxy.1p' -l logfile
complete -c 'dbiproxy.1p' -l mode
complete -c 'dbiproxy.1p' -l pidfile
complete -c 'dbiproxy.1p' -l version

