# edit
# Autogenerated from man page /usr/share/man/man1/edit.1.gz
complete -c edit -o ccommand -d 'Execute  command when editing begins'
complete -c edit -s l -d 'Start in a special mode useful for the  Lisp programming language'
complete -c edit -s r -s L -d 'When no argument is supplied with this option, all files to be recovered are …'
complete -c edit -s R -d 'Files are opened read-only when this option is given'
complete -c edit -s s -d 'Script mode; all feedback for interactive editing is disabled'
complete -c edit -s t -d 'Read the  tags file, then choose the file and position specified by  tagstrin…'
complete -c edit -s v -d 'Start in visual mode even if called as R ex '
complete -c edit -s V -d 'Echo command input to standard error, unless it originates from a terminal'
complete -c edit -s w -d 'Specify the size of the editing window for visual mode. \\"	from ex'
complete -c edit -s c -d 'Execute command when editing begins'

