# epsffit
# Autogenerated from man page /usr/share/man/man1/epsffit.1.gz
complete -c epsffit -s c -l center -d 'center the image in the given bounding box'
complete -c epsffit -s r -l rotate -d 'rotate the image by 90 degrees counter-clockwise'
complete -c epsffit -s a -l aspect -d 'adjust the aspect ratio to fit the bounding box'
complete -c epsffit -s m -l maximize -d 'rotate the image to fill more of the page if possible'
complete -c epsffit -s s -l showpage -d 'append a \\,/showpage\\/ to the file to force printing'
complete -c epsffit -l help -d 'display this help and exit'
complete -c epsffit -s v -l version -d 'display version information and exit '

