# evdev-joystick
# Autogenerated from man page /usr/share/man/man1/evdev-joystick.1.gz
complete -c evdev-joystick -l h -l help -d 'Print out a summary of available options'
complete -c evdev-joystick -l l -l listdevs -d 'List all joystick devices found'
complete -c evdev-joystick -l s -l showcal -d 'Show the current calibration for the specified device'
complete -c evdev-joystick -l e -l evdev -d 'Specify the joystick device to modify'
complete -c evdev-joystick -l a -l axis -d 'Specify the axis to modify (by default, all axes are calibrated)'
complete -c evdev-joystick -l m -l minimum -d 'Change the minimum for the current joystick'
complete -c evdev-joystick -l M -l maximum -d 'Change the maximum for the current joystick'
complete -c evdev-joystick -l d -l deadzone -d 'Change the deadzone for the current joystick'
complete -c evdev-joystick -l f -l fuzz -d 'Change the fuzz for the current joystick'

