# extractres
# Autogenerated from man page /usr/share/man/man1/extractres.1.gz
complete -c extractres -s m -l merge -d 'merge resources of the same name into one file (needed e. g'
complete -c extractres -l help -d 'display this help and exit'
complete -c extractres -s v -l version -d 'display version information and exit '

