# ffcfstress
# Autogenerated from man page /usr/share/man/man1/ffcfstress.1.gz
complete -c ffcfstress -s d -d 'The device to test (by default /dev/input/event0)'
complete -c ffcfstress -s u -d 'The update rate in Hz (25 by default)'
complete -c ffcfstress -s f -d 'The spring center motion frequency in Hz (0. 1 by default)'
complete -c ffcfstress -s a -d 'The spring center motion amplitude, between 0. 0 and 1. 0 (1. 0 by default)'
complete -c ffcfstress -s s -d 'The spring strength factor (1. 0 by default)'
complete -c ffcfstress -s x -d 'absolute axis to test (default: 0) '
complete -c ffcfstress -s A -d 'switch off auto-centering'
complete -c ffcfstress -s o -d 'Dummy option, useful when all defaults should be used'

