# fixps
# Autogenerated from man page /usr/share/man/man1/fixps.1.gz
complete -c fixps -s h -l help -d 'display this help and exit'
complete -c fixps -s v -l version -d 'display version information and exit'
complete -c fixps -s q -l quiet -d 'don\'t print informational messages'
complete -c fixps -s o -l output -d 'save result in FILE.   If FILE is `-\', send to stdout'
complete -c fixps -s c -l check -l dry-run -d 'don\'t perform any action AUTHOR Written by Akim Demaille'

