# foomatic-compiledb
# Autogenerated from man page /usr/share/man/man1/foomatic-compiledb.1.gz
complete -c foomatic-compiledb -s t -d 'Output file type, either ppd or xml'
complete -c foomatic-compiledb -s f -d 'Force: Write into the destination directory even if it already exists'
complete -c foomatic-compiledb -s j -d 'n = number of work processes to run driver '

