# foomatic-ppdfile
# Autogenerated from man page /usr/share/man/man1/foomatic-ppdfile.1.gz
complete -c foomatic-ppdfile -s d -d 'The (optional) driver name to use'
complete -c foomatic-ppdfile -s p -d 'printer id The printer id'
complete -c foomatic-ppdfile -s w -d 'Return a PPD file that conforms to the Microsoft Windows format limitations'
complete -c foomatic-ppdfile -s A -d 'Return all printer entries in the database'
complete -c foomatic-ppdfile -s P -d 'Return all printer entries in the database which match the regular expression'

