# foomatic-printjob
# Autogenerated from man page /usr/share/man/man1/foomatic-printjob.1.gz
complete -c foomatic-printjob -s s -d 'Explicit spooler type'
complete -c foomatic-printjob -s P -d 'Any commands specified should apply to this queue instead of the default'
complete -c foomatic-printjob -s o -d 'Set option to value'
complete -c foomatic-printjob -s '#' -d 'Print n copies file1  file2  '
complete -c foomatic-printjob -s Q -d 'Query the jobs in a queue'
complete -c foomatic-printjob -s a -d 'Query the jobs in all queues'
complete -c foomatic-printjob -s R -d 'Remove a job from a queue.   Using - will remove all jobs'
complete -c foomatic-printjob -s C -d 'Execute control commands for queue/job manipulation'
complete -c foomatic-printjob -s i -d 'Interactive mode: You will be asked if foomatic-printjob is in doubt about so…'
complete -c foomatic-printjob -s S -d 'Save the chosen spooler as the default spooler'
complete -c foomatic-printjob -s h -d 'Show this message or show a list of available options if a queue is specified'

