# gdnc
# Autogenerated from man page /usr/share/man/man1/gdnc.1.gz
complete -c gdnc -o NSHost -d argument
complete -c gdnc -o GSPublic -d 'P To run a copy of the server to handle network-public notifications (availab…'
complete -c gdnc -o GSNetwork

