# geoiplookup
# Autogenerated from man page /usr/share/man/man1/geoiplookup.1.gz
complete -c geoiplookup -s f -d 'Specify a custom path to a single GeoIP datafile'
complete -c geoiplookup -s d -d 'Specify a custom directory containing GeoIP datafile(s)'
complete -c geoiplookup -s v -d 'Lists the date and build number for the GeoIP datafile(s)'

