# grub-btrfsd
# Autogenerated from man page /usr/share/man/man8/grub-btrfsd.8.bz2
complete -c grub-btrfsd -s c -l no-color
complete -c grub-btrfsd -s l -l log-file
complete -c grub-btrfsd -s r -l recursive
complete -c grub-btrfsd -s s -l syslog
complete -c grub-btrfsd -s t -l timeshift-auto
complete -c grub-btrfsd -s o -l timeshift-old
complete -c grub-btrfsd -s v -l verbose
complete -c grub-btrfsd -s h -l help

