# hg
# Autogenerated from man page /usr/share/man/man1/hg.1.gz
complete -c hg -s R -l repository -d ' repository root directory or name of overlay bundle file'
complete -c hg -l cwd -d ' change working directory'
complete -c hg -s y -l noninteractive -d ' do not prompt, automatically pick the first choice for all prompts'
complete -c hg -s q -l quiet -d ' suppress output'
complete -c hg -s v -l verbose -d ' enable additional output'
complete -c hg -l color -d ' when to colorize (boolean, always, auto, never, or debug)'
complete -c hg -l config -d ' set/override config option (use \\(aqsection. name=value\\(aq)'
complete -c hg -l debug -d ' enable debugging output'
complete -c hg -l debugger -d ' start debugger'
complete -c hg -l encoding -d ' set the charset encoding (default: UTF-8)'
complete -c hg -l encodingmode -d ' set the charset encoding mode (default: strict)'
complete -c hg -l traceback -d ' always print a traceback on exception'
complete -c hg -l time -d ' time how long the command takes'
complete -c hg -l profile -d ' print command execution profile'
complete -c hg -l version -d ' output version information and exit'
complete -c hg -s h -l help -d ' display help and exit'
complete -c hg -l hidden -d ' consider hidden changesets'
complete -c hg -l pager -d ' when to paginate (boolean, always, auto, or never) (default: auto)'
complete -c hg -o U/--noupdate
complete -c hg -l pull
complete -c hg -s U -l noupdate
complete -c hg -s u -l updaterev
complete -c hg -s r -l rev
complete -c hg -s b -l branch
complete -c hg -l uncompressed
complete -c hg -l stream
complete -c hg -s e -l ssh
complete -c hg -l remotecmd
complete -c hg -l insecure
complete -c hg -s f -l force
complete -c hg -s n -l newest-first
complete -c hg -l bundle
complete -c hg -s B -l bookmarks
complete -c hg -s p -l patch
complete -c hg -s g -l git
complete -c hg -s l -l limit
complete -c hg -s M -l no-merges
complete -c hg -l stat
complete -c hg -s G -l graph
complete -c hg -l style
complete -c hg -s T -l template
complete -c hg -s S -l subrepos
complete -c hg -l update
complete -c hg -l confirm
complete -c hg -l bookmark
complete -c hg -l remote-hidden
complete -c hg -l pushvars -d 'HG_USERVAR_ENABLE_FEATURE=true as part of their environment'
complete -c hg -l all-bookmarks
complete -c hg -l new-branch
complete -c hg -l publish
complete -c hg -s A -l accesslog
complete -c hg -s d -l daemon
complete -c hg -l daemon-postexec
complete -c hg -s E -l errorlog
complete -c hg -l port
complete -c hg -s a -l address
complete -c hg -l prefix
complete -c hg -l name
complete -c hg -l web-conf
complete -c hg -l webdir-conf
complete -c hg -l pid-file
complete -c hg -l stdio
complete -c hg -l cmdserver
complete -c hg -s t -l templates
complete -c hg -s 6 -l ipv6
complete -c hg -l certificate
complete -c hg -l print-url
complete -c hg -l addremove
complete -c hg -l close-branch
complete -c hg -l amend
complete -c hg -s s -l secret
complete -c hg -l draft
complete -c hg -l edit
complete -c hg -l force-close-branch
complete -c hg -s i -l interactive
complete -c hg -s I -l include
complete -c hg -s X -l exclude
complete -c hg -s m -l message
complete -c hg -l logfile
complete -c hg -l date
complete -c hg -l user
complete -c hg -l dry-run
complete -c hg -l merge
complete -c hg -l commit
complete -c hg -l no-commit
complete -c hg -l parent
complete -c hg -l tool
complete -c hg -l keep
complete -c hg -l base
complete -c hg -s c -l continue
complete -c hg -l stop
complete -c hg -l abort
complete -c hg -l log
complete -c hg -s D -l currentdate
complete -c hg -l currentuser
complete -c hg -s P -l preview
complete -c hg -l delete
complete -c hg -l rename
complete -c hg -l inactive
complete -c hg -l list
complete -c hg -s C -l clean
complete -c hg -l active
complete -c hg -l closed
complete -c hg -l public
complete -c hg -o f/--force -d changeset
complete -c hg -l local
complete -c hg -l remove
complete -c hg -l follow
complete -c hg -l no-follow
complete -c hg -l text
complete -c hg -l file
complete -c hg -l number
complete -c hg -l changeset
complete -c hg -l line-number
complete -c hg -l skip
complete -c hg -s w -l ignore-all-space
complete -c hg -l ignore-space-change
complete -c hg -l ignore-blank-lines
complete -c hg -s Z -l ignore-space-at-eol
complete -c hg -s o -l output
complete -c hg -l decode
complete -c hg -l forget
complete -c hg -l after
complete -c hg -l at-rev
complete -c hg -l from
complete -c hg -l to
complete -c hg -l change
complete -c hg -l binary
complete -c hg -l nodates
complete -c hg -l noprefix
complete -c hg -l show-function
complete -c hg -l reverse
complete -c hg -l unified
complete -c hg -l root
complete -c hg -s 0 -l print0
complete -c hg -l all
complete -c hg -l diff
complete -c hg -l ignore-case
complete -c hg -l files-with-matches
complete -c hg -l all-files
complete -c hg -l reset
complete -c hg -l good
complete -c hg -l bad
complete -c hg -l extend
complete -c hg -l command
complete -c hg -l topo
complete -c hg -l num
complete -c hg -l id
complete -c hg -l tags
complete -c hg -l follow-first
complete -c hg -l copies
complete -c hg -s k -l keyword
complete -c hg -s L -l line-range
complete -c hg -l removed
complete -c hg -l only-merges
complete -c hg -l only-branch
complete -c hg -l prune
complete -c hg -l similarity
complete -c hg -l fullpath
complete -c hg -l abort-on-err
complete -c hg -l ignored
complete -c hg -l dirs
complete -c hg -l files
complete -c hg -l print
complete -c hg -o A/--after -d 'been deleted, -f/--force can be used to force deletion, and -Af can be used t…'
complete -c hg -o Af -d 'T}	T{ R T}	T{ R T}	T{ R T}	T{ R T} _'
complete -c hg -l mark
complete -c hg -l unmark
complete -c hg -l no-status
complete -c hg -l re-merge
complete -c hg -l no-backup
complete -c hg -l unknown
complete -c hg -l cleanup
complete -c hg -o c/--clean -o i/--ignored -o C/--copies -o A/--all -d 'Unless options described with "show only '
complete -c hg -l modified
complete -c hg -l added
complete -c hg -l deleted
complete -c hg -l terse
complete -c hg -l remote
complete -c hg -l check
complete -c hg -l no-decode
complete -c hg -l type
complete -c hg -l exact
complete -c hg -l switch-parent
complete -c hg -l bypass -d changes
complete -c hg -l strip
complete -c hg -l partial
complete -c hg -l import-branch
complete -c hg -l option
complete -c hg -l verify
complete -c hg -l full
complete -c hg -l global -d 'repository-level config file'
complete -c hg -l non-shared -d 'This file is not shared across shares when in share-safe mode'
complete -c hg -l untrusted
complete -c hg -l exp-all-known
complete -c hg -l source
complete -c hg -l shared
complete -c hg -l extension
complete -c hg -l system
complete -c hg -o DAYS
complete -c hg -l flagname
complete -c hg -o ffoo -d 'This syntax applies to all non-boolean flags (strings, numbers or lists)'
complete -c hg -s 2
complete -c hg -s '>'
complete -c hg -l no-use-pep517 -d 'the legacy setup. py system'
complete -c hg -o T/--template
complete -c hg -o v/--verbose -d 'increase the amount of data exposed by Mercurial'
complete -c hg -o S/--subrepos -d 'path of a directory in a subrepo, addremove will be performed on it even with…'
complete -c hg -l apply-changes
complete -c hg -l print-changes
complete -c hg -l edit-lines
complete -c hg -l note
complete -c hg -l tombstone
complete -c hg -l changesets
complete -c hg -l oldtemplate
complete -c hg -l dateformat
complete -c hg -l sort
complete -c hg -l diffstat
complete -c hg -l aliases
complete -c hg -l background
complete -c hg -l branchsort
complete -c hg -l datesort
complete -c hg -l sourcesort
complete -c hg -l closesort
complete -c hg -l authors
complete -c hg -l source-type
complete -c hg -l dest-type
complete -c hg -l authormap
complete -c hg -l filemap
complete -c hg -l splicemap
complete -c hg -l branchmap
complete -c hg -l program
complete -c hg -l per-file
complete -c hg -l import-marks
complete -c hg -l export-marks
complete -c hg -l force-editor
complete -c hg -l working-dir
complete -c hg -l whole
complete -c hg -l key
complete -c hg -l commands
complete -c hg -l edit-plan
complete -c hg -l outgoing
complete -c hg -l commits
complete -c hg -l default
complete -c hg -l rcfile
complete -c hg -l ignore
complete -c hg -l large -d '$ dd if=/dev/urandom of=randomdata count=2000 $ hg add --large randomdata $ h…'
complete -c hg -l lfsize -d '[largefiles] minsize = 2'
complete -c hg -l size
complete -c hg -l to-normal
complete -c hg -l patches
complete -c hg -o c/--create-repo -d 'repository for patches (qinit -c may also be run later to convert an unversio…'
complete -c hg -l create-repo
complete -c hg -o X/--exclude -d 'only changes to matching files to the new patch, leaving the rest as uncommit…'
complete -c hg -o u/--user -o d/--date -d 'date, respectively'
complete -c hg -o e/--edit -o m/--message -o l/--logfile -d 'well as the commit message'
complete -c hg -l short
complete -c hg -s 1 -l last
complete -c hg -l summary
complete -c hg -l applied
complete -c hg -l keep-changes
complete -c hg -l none
complete -c hg -l move
complete -c hg -l create
complete -c hg -l purge
complete -c hg -l copy
complete -c hg -l empty
complete -c hg -l pop -d 'guarded patches'
complete -c hg -l series
complete -c hg -l reapply
complete -c hg -l missing
complete -c hg -l first
complete -c hg -l existing
complete -c hg -l push
complete -c hg -l import-rules -d 'add --addinclude, --addexclude rules in bulk'
complete -c hg -l addinclude
complete -c hg -l removeinclude
complete -c hg -l auto-remove-includes
complete -c hg -l addexclude
complete -c hg -l removeexclude
complete -c hg -l clear
complete -c hg -l force-delete-local-changes
complete -c hg -l backup
complete -c hg -l update-working-copy
complete -c hg -o a/--attach -o i/--inline -l body
complete -c hg -l plain
complete -c hg -l bundlename
complete -c hg -l intro
complete -c hg -l attach
complete -c hg -l inline
complete -c hg -l bcc
complete -c hg -l cc
complete -c hg -l desc
complete -c hg -l test
complete -c hg -l mbox
complete -c hg -l reply-to
complete -c hg -l subject
complete -c hg -l in-reply-to
complete -c hg -l flag
complete -c hg -l stack
complete -c hg -l test-vcr
complete -c hg -l reviewer
complete -c hg -l blocker
complete -c hg -l comment
complete -c hg -l fold
complete -c hg -l accept
complete -c hg -l reject
complete -c hg -l request-review
complete -c hg -l abandon
complete -c hg -l reclaim
complete -c hg -l close
complete -c hg -l reopen
complete -c hg -l plan-changes
complete -c hg -l resign
complete -c hg -l commandeer
complete -c hg -l dest
complete -c hg -l collapse
complete -c hg -l keepbranches
complete -c hg -l detach
complete -c hg -l auto-orphans
complete -c hg -l ----------
complete -c hg -l repack
complete -c hg -l incremental
complete -c hg -l packsonly
complete -c hg -l decompress
complete -c hg -l relative
complete -c hg -l rebase
complete -c hg -l source/-s -d 'just as if it temporarily had been pulled'
complete -c hg -l continue/-c
complete -c hg -l filter
complete -c hg -l allow-dirty-working-copy

