# HTMLLinker
# Autogenerated from man page /usr/share/man/man1/HTMLLinker.1.gz
complete -c HTMLLinker -l help -d 'Prints a short list of available options'
complete -c HTMLLinker -l version -d 'Displays version information'
complete -c HTMLLinker -l verbose -d 'Prints additional information while processing'
complete -c HTMLLinker -o Warn -d 'Print additional information about unresolved links'
complete -c HTMLLinker -o LinksMarker -d 'Only fix links with attribute rel\\f\\=xxx'
complete -c HTMLLinker -o FixupAllLinks -d 'Attempt to fix all links (not only those that are marked with -LinksMarker'
complete -c HTMLLinker -o PathMappingsFile -d 'Read the relocation mappings from  file (in dictionary format)'
complete -c HTMLLinker -o PathMappings -d 'Use the specified path mappings'
complete -c HTMLLinker -s l -d and
complete -c HTMLLinker -s d -d 'options are allowed):'
complete -c HTMLLinker -o BuildRelocationFileForDir -d 'Build a relocation file for the directory dir and save it into dir/table'

