# includeres
# Autogenerated from man page /usr/share/man/man1/includeres.1.gz
complete -c includeres -l help -d 'display this help and exit'
complete -c includeres -s v -l version -d 'display version information and exit '

