# ipsec
# Autogenerated from man page /usr/share/man/man8/ipsec.8.gz
complete -c ipsec -l utc -d 'returns a list of RSA public keys that were either loaded in raw key format o…'
complete -c ipsec -l help -d 'returns the usage information for the  ipsec command'
complete -c ipsec -l version -d 'returns the version in the form of  Linux strongSwan U<strongSwan userland ve…'
complete -c ipsec -l versioncode -d 'returns the version number in the form of  U<strongSwan userland version>/K<L…'
complete -c ipsec -l copyright -d 'returns the copyright information'
complete -c ipsec -l directory -d 'returns the LIBEXECDIR directory as defined by the configure options'
complete -c ipsec -l confdir -d 'returns the SYSCONFDIR directory as defined by the configure options'
complete -c ipsec -l piddir -d 'returns the PIDDIR directory as defined by the configure options'

