# irpty
# Autogenerated from man page /usr/share/man/man1/irpty.1.gz
complete -c irpty -s h -l help -d 'display usage summary'
complete -c irpty -s V -l version -d 'display version'
complete -c irpty -s e -l no-echo -d 'disable echo'
complete -c irpty -s i -l ignore-eof -d 'ignore EOF'
complete -c irpty -s n -l non-interactive -d 'force non-interactive mode'
complete -c irpty -s v -l verbose -d 'verbose mode SEE ALSO'

