# irsend
# Autogenerated from man page /usr/share/man/man1/irsend.1.gz
complete -c irsend -s h -l help -d 'Display usage summary'
complete -c irsend -s v -l version -d 'Display version'
complete -c irsend -s d -l device -d 'Use given lircd socket [/var/run/lirc/lircd]'
complete -c irsend -s a -l address -d 'Connect to lircd at this address'
complete -c irsend -s '#' -l count -d 'Send command n times'

