# irsimsend
# Autogenerated from man page /usr/share/man/man1/irsimsend.1.gz
complete -c irsimsend -s c -l count -d 'Repeat each sent signal <count> times'
complete -c irsimsend -s U -l plugindir -d 'Load drivers from path, a \':\' separated search path similar to $PATH'
complete -c irsimsend -s l -l listfile -d 'Send symbols listed in file instead of just the symbols in the config file'
complete -c irsimsend -s k -l keysym -d 'Send a single key symbol defined in file'
complete -c irsimsend -s s -l start-space -d 'Send an initial space before sending data'
complete -c irsimsend -s v -l version -d 'Print version and exit'
complete -c irsimsend -s h -l help -d 'Print help message'

