# irsimreceive
# Autogenerated from man page /usr/share/man/man1/irsimreceive.1.gz
complete -c irsimreceive -s U -l plugindir -d 'Load drivers from <dir>'
complete -c irsimreceive -s v -l version -d 'Print version and exit'
complete -c irsimreceive -s h -l help -d 'Print help message'

