# irtestcase
# Autogenerated from man page /usr/share/man/man1/irtestcase.1.gz
complete -c irtestcase -s l -l lircrc -d 'Log also applications strings (as ircat(1)) using lircrc type config file'
complete -c irtestcase -s p -l prog -d 'When using -l/--lircrc, the program name matching the PROG = entries in lircrc'
complete -c irtestcase -s t -l testdata -d 'Use data i file instead of "live" input from the remote'
complete -c irtestcase -s v -l version -d 'Print version and exit'
complete -c irtestcase -s h -l help -d 'Print help message'

