# irxevent
# Autogenerated from man page /usr/share/man/man1/irxevent.1.gz
complete -c irxevent -s d -l daemon -d 'Fork and run in background'
complete -c irxevent -s h -l help -d 'Display usage summary'
complete -c irxevent -s V -l version -d 'Display version FILES'

