# jscal
# Autogenerated from man page /usr/share/man/man1/jscal.1.gz
complete -c jscal -s c -l calibrate -d 'Calibrate the joystick'
complete -c jscal -s h -l help -d 'Print out a summary of available options'
complete -c jscal -s b -d 'Specify a button to use to continue'
complete -c jscal -s s -l set-correction -d 'Sets correction to specified values'
complete -c jscal -s u -l set-mappings -d 'Sets axis and button mappings'
complete -c jscal -s t -l test-center -d 'Tests if the joystick is correctly calibrated'
complete -c jscal -s V -l version -d 'Prints the version numbers of the running joystick driver and that which jsca…'
complete -c jscal -s p -l print-correction -d 'Prints the current correction settings'
complete -c jscal -s q -l print-mappings -d 'Prints the current axis and button mappings'

