# jstest
# Autogenerated from man page /usr/share/man/man1/jstest.1.gz
complete -c jstest -l normal -d 'One-line mode showing immediate status'
complete -c jstest -l old -d 'Same as --normal, using 0. x interface'
complete -c jstest -l event -d 'Prints events as they come in'
complete -c jstest -l nonblock -d 'Same as --event, in nonblocking mode'
complete -c jstest -l select -d 'Same as --event, using select(2) call.  SEE ALSO fftest(1), jscal(1)'

