# kate
# Autogenerated from man page /usr/share/man/man1/kate.1.gz
complete -c kate -s s -l start -d 'Start Kate with a given session'
complete -c kate -l startanon -d 'Start Kate with a new anonymous session, implies -n'
complete -c kate -s n -l new -d 'Force start of a new Kate instance (is ignored if start is used and another K…'
complete -c kate -s b -l block -d 'If using an already running Kate instance, block until it exits, if URLs give…'
complete -c kate -s p -l pid -d 'Only try to reuse kate instance with this pid (is ignored if start is used an…'
complete -c kate -s e -l encoding -d 'Set encoding for the file to open'
complete -c kate -s l -l line -d 'Navigate to this line'
complete -c kate -s c -l column -d 'Navigate to this column'
complete -c kate -s i -l stdin -d 'Read the contents of stdin'
complete -c kate -l tempfile -d 'The files/URLs opened by the application will be deleted after use'

