# ldapvc
# Autogenerated from man page /usr/share/man/man1/ldapvc.1.gz
complete -c ldapvc -s V -d 'Print version info.  If -VV is given, only the version information is printed'
complete -c ldapvc -s d -d 'Set the LDAP debugging level to debuglevel'
complete -c ldapvc -s a -d 'Print the authzID resulting from a successful verification of credentials'
complete -c ldapvc -s b -d 'Print the results from the ppolicy control after verification of credentials'
complete -c ldapvc -s n -d 'Show what would be done, but don\'t actually perform the operation'
complete -c ldapvc -s v -d 'Run in verbose mode, with many diagnostics written to standard output'
complete -c ldapvc -s x -d 'Use simple authentication instead of SASL'
complete -c ldapvc -s D -d 'Use the Distinguished Name binddn to bind to the LDAP directory'
complete -c ldapvc -s W -d 'Prompt for simple authentication'
complete -c ldapvc -s w -d 'Use passwd as the password for simple authentication'
complete -c ldapvc -s y -d 'Use complete contents of passwdfile as the password for simple authentication'
complete -c ldapvc -s H -d 'Specify URI(s) referring to the ldap server(s); only the protocol/host/port f…'
complete -c ldapvc -s E -d 'Specify general extensions with -e and Verify Credentials extensions with -E'
complete -c ldapvc -s o -d 'Specify any  ldap. conf (5) option or one of the following: '
complete -c ldapvc -s O -d 'Specify SASL security properties'
complete -c ldapvc -s I -d 'Enable SASL Interactive mode.   Always prompt'
complete -c ldapvc -s Q -d 'Enable SASL Quiet mode.   Never prompt'
complete -c ldapvc -s N -d 'Do not use reverse DNS to canonicalize SASL host name'
complete -c ldapvc -s U -d 'Specify the authentication ID for SASL bind'
complete -c ldapvc -s R -d 'Specify the realm of authentication ID for SASL bind'
complete -c ldapvc -s X -d 'Specify the requested authorization ID for SASL bind'
complete -c ldapvc -s Y -d 'Specify the SASL mechanism to be used for authentication'
complete -c ldapvc -s e
complete -c ldapvc -s Z -d 'Issue StartTLS (Transport Layer Security) extended operation.  If you use'
complete -c ldapvc -o ZZ -d EXAMPLE

