# lha
# Autogenerated from man page /usr/share/man/man1/lha.1.gz
complete -c lha -s l -d 'List contents of the specified archive'
complete -c lha -s v -d 'Verbosely list contents of the specified archive'
complete -c lha -s t -d 'Test the integrity of the specified archive: decompress its contents and chec…'
complete -c lha -s e -s x -d 'Extract archive'

