# libnbd-release-notes-1.18
# Autogenerated from man page /usr/share/man/man1/libnbd-release-notes-1.18.1.gz
complete -c 'libnbd-release-notes-1.18' -s 1 -d 'client code in libnbd itself is affected by this, it could affect external cl…'

