# lircrcd
# Autogenerated from man page /usr/share/man/man8/lircrcd.8.gz
complete -c lircrcd -s h -l help -d 'Display help message'
complete -c lircrcd -s v -l version -d 'Display version'
complete -c lircrcd -s p -l permission -d 'The --permission option gives the file permission of the Unix domain socket l…'
complete -c lircrcd -s o -l output -d 'With the --output option you can select the Unix domain socket, which lircrcd…'

