# lircmd
# Autogenerated from man page /usr/share/man/man8/lircmd.8.gz
complete -c lircmd -s h -l help -d 'Display help  message'
complete -c lircmd -s v -l version -d 'Display version'
complete -c lircmd -s n -l nodaemon -d 'Don\'t fork to background'
complete -c lircmd -s s -l socket -d 'Use alternate lircd socket path (the lircmd input source)'
complete -c lircmd -s O -l options-file -d 'Alternative default options file, usually defaults to /etc/lirc/lirc_options'
complete -c lircmd -s u -l uinput -d 'On Linux systems the --uinput option will enable automatic generation of Linu…'
complete -c lircmd -s D -l loglevel -d 'Determine the amount of logging information'

