# lircd-uinput
# Autogenerated from man page /usr/share/man/man8/lircd-uinput.8.gz
complete -c lircd-uinput -s u -l uinput -d 'uinput kernel device, defaults to /dev/uinput'
complete -c lircd-uinput -s r -l release-suffix -d 'lircd-uinput generates different events depending on if the button name ends …'
complete -c lircd-uinput -s R -l repeat -d 'Set kernel autorepeat parameters of the created  /dev/input/event device'
complete -c lircd-uinput -s a -l add-release-events -d 'Generate synthetic release events'
complete -c lircd-uinput -s d -l disabled -d 'The path of a file which contains name of buttons to be disabled, one per line'
complete -c lircd-uinput -s O -l options-file -d 'Options file holding default values.  Defaults to  /etc/lircd/lirc_options'
complete -c lircd-uinput -s L -l logfile -d 'Select the log file, either the string \'syslog\' indicating that syslog(1) sho…'
complete -c lircd-uinput -s D -l loglevel -d 'Determine the amount of logging information'
complete -c lircd-uinput -s h -l help -d 'Display usage summary'
complete -c lircd-uinput -l release -d option
complete -c lircd-uinput -s v -l version -d 'Display version info'

