# lloadd
# Autogenerated from man page /usr/share/man/man8/lloadd.8.gz
complete -c lloadd -s 4 -d 'Listen on IPv4 addresses only'
complete -c lloadd -s 6 -d 'Listen on IPv6 addresses only'
complete -c lloadd -s d -d 'Turn on debugging as defined by R debug-level '
complete -c lloadd -s s -d 'This option tells  lloadd at what debug-level debugging statements should be …'
complete -c lloadd -s n -d 'Specifies the service name for logging and other purposes'
complete -c lloadd -s l -d 'Selects the local user of the  syslog (8) facility'
complete -c lloadd -s f -d 'Specifies the lloadd configuration file'
complete -c lloadd -s h -d 'lloadd will by default serve  ldap:/// (LDAP over TCP on all interfaces on de…'
complete -c lloadd -s r -d 'Specifies a directory to become the root directory'
complete -c lloadd -s u -d 'lloadd will run lloadd with the specified user name or id, and that user\'s su…'
complete -c lloadd -s g -d 'lloadd will run with the specified group name or id'
complete -c lloadd -s o -d 'This option provides a generic means to specify options without the need to r…'

