# lp2
# Autogenerated from man page /usr/share/man/man1/lp2.1.gz
complete -c lp2 -s h -l help -d 'display this help and exit'
complete -c lp2 -s V -l version -d 'display version information and exit'
complete -c lp2 -s f -l front -d 'print only the front pages (recto)'
complete -c lp2 -s b -l back -d 'print only the back pages (verso) AUTHOR Written by Reuben Thomas'

