# lv2apply
# Autogenerated from man page /usr/share/man/man1/lv2apply.1.gz
complete -c lv2apply -s V -d 'Display version information and exit.  Pp'
complete -c lv2apply -s c -d 'Set control port symbol to value.  Pp'
complete -c lv2apply -s h -d 'Print the command line options.  Pp'
complete -c lv2apply -s i -d 'Input file path.  Pp'
complete -c lv2apply -s o -d 'Output file path'

