# markdown
# Autogenerated from man page /usr/share/man/man1/markdown.1.gz
complete -c markdown -s b -d 'Links in source beginning with / will be prefixed with url-base in the output'
complete -c markdown -s C -d 'When processing markdown extra-style footnotes, use the given prefix instead …'
complete -c markdown -s d -d 'Instead of writing the html file, dump a parse tree to stdout'
complete -c markdown -s f -d 'Set or clear various translation flags'
complete -c markdown -s F -d 'Set translation flags'
complete -c markdown -s n -d 'Don\'t write generated html'
complete -c markdown -s o -d 'Write the generated html to file'
complete -c markdown -s S -d 'output <style> blocks'
complete -c markdown -s V -d 'Show the version# and compile-time configuration data'
complete -c markdown -o VV -d 'Show the version#, the compile-time configuration, and the run-time configura…'
complete -c markdown -s t -d 'Use mkd_text 3 to format text instead of processing stdin with the markdown 3…'
complete -c markdown -s T -d 'If run with the table-of-content flag on, dump the table of contents before t…'
complete -c markdown -s s -d 'Use the markdown 3 function to format text'
complete -c markdown -o toc -d 'Set the table-of-content flag, then dump the table of contents before the for…'

