# mimeopen.1p
# Autogenerated from man page /usr/share/man/man1/mimeopen.1p.gz
complete -c 'mimeopen.1p' -s a -l ask -d 'X Item "-a, --ask" Do not execute the default application but ask which appli…'
complete -c 'mimeopen.1p' -s d -l ask-default -d 'X Item "-d, --ask-default" Let the user choose a new default program for give…'
complete -c 'mimeopen.1p' -s n -l no-ask -d 'X Item "-n, --no-ask" Don\'t ask the user which program to use'
complete -c 'mimeopen.1p' -s M -l magic-only -d 'X Item "-M, --magic-only" Do not check for extensions, globs or inode type, o…'
complete -c 'mimeopen.1p' -l database -d 'X Item "--database=mimedir:mimedir:'
complete -c 'mimeopen.1p' -s D -l debug -d 'X Item "-D, --debug" Print debug information about how the mimetype was deter…'
complete -c 'mimeopen.1p' -s h -l help -d 'X Item "-h, --help"'
complete -c 'mimeopen.1p' -s u -l usage -d 'X Item "-u, --usage" . PD Print a help message and exits'
complete -c 'mimeopen.1p' -s v -l version
complete -c 'mimeopen.1p' -s L -l dereference

