# mimetype.1p
# Autogenerated from man page /usr/share/man/man1/mimetype.1p.gz
complete -c 'mimetype.1p' -s a -l all -d 'X Item "-a, --all" Show output of all rules that match the file'
complete -c 'mimetype.1p' -s b -l brief -d 'X Item "-b, --brief" Do not prepend filenames to output lines (brief mode)'
complete -c 'mimetype.1p' -l database -d 'X Item "--database=mimedir:mimedir:'
complete -c 'mimetype.1p' -s d -l describe -d 'X Item "-d, --describe" Print file descriptions instead of mime types, this i…'
complete -c 'mimetype.1p' -s D -l debug -d 'X Item "-D, --debug" Print debug information about how the mimetype was deter…'
complete -c 'mimetype.1p' -s f -l namefile -d 'X Item "-f namefile, --namefile=namefile" Read the names of the files to be e…'
complete -c 'mimetype.1p' -l file-compat -d 'X Item "--file-compat" Make mimetype behave a little more file\\|(1) compatible'
complete -c 'mimetype.1p' -s F -l separator -d 'X Item "-F string, --separator=string" Use string as custom separator between…'
complete -c 'mimetype.1p' -s h -l help -d 'X Item "-h, --help"'
complete -c 'mimetype.1p' -s u -l usage -d 'X Item "-u, --usage" . PD Print a help message and exits'
complete -c 'mimetype.1p' -s i -l mimetype -d 'X Item "-i, --mimetype" Use mime types, opposite to "--describe", this is the…'
complete -c 'mimetype.1p' -s L -l dereference -d 'X Item "-L, --dereference" Follow symbolic links'
complete -c 'mimetype.1p' -s l -l language -d 'X Item "-l code, --language=code" The language attribute specifies a two lett…'
complete -c 'mimetype.1p' -s M -l magic-only -d 'X Item "-M, --magic-only" Do not check for extensions, globs or inode type, o…'
complete -c 'mimetype.1p' -s N -l noalign -d 'X Item "-N, --noalign" Do not align output fields'
complete -c 'mimetype.1p' -l output-format -d 'X Item "--output-format" If you want an alternative output format, you can sp…'
complete -c 'mimetype.1p' -l stdin -d 'X Item "--stdin" Determine type of content from STDIN, less powerful then nor…'
complete -c 'mimetype.1p' -s v -l version

