# mkd2html
# Autogenerated from man page /usr/share/man/man1/mkd2html.1.gz
complete -c mkd2html -o css -d 'Specifies a CSS file'
complete -c mkd2html -o header -d 'Specifies a line to add to the <header> tag'
complete -c mkd2html -o footer -d 'Specifies a line to add before the <\\/body> tag'

