# mode2
# Autogenerated from man page /usr/share/man/man1/mode2.1.gz
complete -c mode2 -s d -l device -d 'Read from given device'
complete -c mode2 -s H -l driver -d 'Use given driver'
complete -c mode2 -s m -l mode -d 'Write pulse/space data as raw config files.  Does not affect LIRCCODE drivers'
complete -c mode2 -s s -l scope -d 'Enable \'scope like display with time us per char'
complete -c mode2 -s k -l keep-root -d 'Don\'t drop root privileges after opening device.  See RUNNING AS ROOT'
complete -c mode2 -s l -l list-devices -d 'List all available devices for given driver'
complete -c mode2 -s g -l gap -d 'Treat spaces longer than time as the gap.  Time is in microseconds'
complete -c mode2 -s r -l raw -d 'Access device directly'
complete -c mode2 -s A -l driver-options -d 'Set driver-specific option named key to given value'
complete -c mode2 -s U -l plugindir -d 'Load drivers from directory.  See DRIVER LOADING'
complete -c mode2 -s O -l options-file -d 'File containing default values for all options'
complete -c mode2 -s D -l loglevel -d 'Determine the amount of logging information'
complete -c mode2 -s h -l help -d 'Display usage summary'
complete -c mode2 -s v -l version -d 'Display version'

