# multixterm
# Autogenerated from man page /usr/share/man/man1/multixterm.1.gz
complete -c multixterm -o xa -d 'The optional -xa argument indicates arguments to pass to xterm'
complete -c multixterm -o xc -d 'The optional -xc argument indicates a command to be run in each named xterm (…'
complete -c multixterm -o xd -d 'The optional -xd argument indicates a directory to search for files that will…'
complete -c multixterm -o xf -d 'The optional -xf argument indicates a file to be read at startup'
complete -c multixterm -o xn -d 'The optional -xn argument indicates a name for each xterm'
complete -c multixterm -o xv -d 'The optional -xv flag puts multixterm into a verbose mode where it will descr…'
complete -c multixterm -o name -d 'make them easy to remember, all the multixterm flags begin with -x'

