# nbddump
# Autogenerated from man page /usr/share/man/man1/nbddump.1.gz
complete -c nbddump -l help -d 'X Item "--help" Display brief command line help and exit'
complete -c nbddump -l color -d 'X Item "--color"'
complete -c nbddump -l colour -d 'X Item "--colour"'
complete -c nbddump -l no-color -d 'X Item "--no-color"'
complete -c nbddump -l no-colour -d 'X Item "--no-colour" . PD Enable or disable ANSI colours in output'
complete -c nbddump -l length -d 'X Item "--length=N"'
complete -c nbddump -s n -d 'X Item "-n N" . PD Dump up to N bytes and then stop'
complete -c nbddump -s V -d 'X Item "-V"'
complete -c nbddump -l version -d 'Display the package name and version and exit.  SEE ALSO'

