# nbdfuse
# Autogenerated from man page /usr/share/man/man1/nbdfuse.1.gz
complete -c nbdfuse -l help -d 'X Item "--help" Display brief command line help and exit'
complete -c nbdfuse -s C -d 'X Item "-C N"'
complete -c nbdfuse -l connections -d 'X Item "--connections N" '
complete -c nbdfuse -l fuse-help -d 'X Item "--fuse-help" Display FUSE options and exit.   See -o below'
complete -c nbdfuse -s o -d 'X Item "-o FUSE-OPTION" Pass extra options to FUSE'
complete -c nbdfuse -s P -d 'X Item "-P PIDFILE"'
complete -c nbdfuse -l pidfile -d 'X Item "--pidfile PIDFILE" '
complete -c nbdfuse -s r -d 'X Item "-r"'
complete -c nbdfuse -l readonly -d 'X Item "--readonly" . PD Access the network block device read-only'
complete -c nbdfuse -s s -d 'X Item "-s" Use single-threaded FUSE operations.  See "THREAD MODEL" below'
complete -c nbdfuse -s v -d 'X Item "-v"'
complete -c nbdfuse -l verbose -d 'X Item "--verbose"'
complete -c nbdfuse -s d -d 'X Item "-d" . PD Enable verbose messages to stderr'
complete -c nbdfuse -s V -d 'X Item "-V"'
complete -c nbdfuse -l fd -d 'multi-conn (use nbdinfo(1) to query what the server supports)'
complete -c nbdfuse -l version -d 'Display the package name and version and exit.  MODES'

