# nbdsh
# Autogenerated from man page /usr/share/man/man1/nbdsh.1.gz
complete -c nbdsh -s h -d 'X Item "-h"'
complete -c nbdsh -l help -d 'X Item "--help" . PD Display brief command line help and exit'
complete -c nbdsh -l base-allocation -d 'X Item "--base-allocation" Request the use of the "base:allocation" meta cont…'
complete -c nbdsh -s c -d 'X Item "-c \'COMMAND . \'"'
complete -c nbdsh -l command -d 'X Item "--command \'COMMAND . \'" '
complete -c nbdsh -s n -d 'X Item "-n" Do not create the implicit handle \\f(CW\\*(C`h\\*(C\''
complete -c nbdsh -l opt-mode -d 'X Item "--opt-mode" Request that option mode be enabled, which gives fine-gra…'
complete -c nbdsh -s u -d 'X Item "-u URI"'
complete -c nbdsh -l uri -d 'X Item "--uri URI" . PD Connect to the given NBD URI'
complete -c nbdsh -s v -d 'X Item "-v"'
complete -c nbdsh -l verbose -d 'X Item "--verbose" . PD Enable verbose libnbd messages'
complete -c nbdsh -s V -d 'X Item "-V"'
complete -c nbdsh -l version -d 'Display the package name and version and exit.  NOTES'

