# nping
# Autogenerated from man page /usr/share/man/man1/nping.1.gz
complete -c nping -s c
complete -c nping -l tcp -d 'to specify TCP Probe Mode,'
complete -c nping -s p -d 'to specify the target ports; and then the two target hostnames'
complete -c nping -l '>' -d 'SH "OPTIONS SUMMARY"'
complete -c nping -l delay -d 'option.  These examples show how it works.  # nping --tcp -c 2 1. 1. 1'
complete -c nping -l tcp-connect
complete -c nping -l udp
complete -c nping -l icmp
complete -c nping -l arp
complete -c nping -l traceroute
complete -c nping -l dest-port
complete -c nping -o p- -d 'to target ports from 1 through 65535'
complete -c nping -s g -l source-port
complete -c nping -l seq
complete -c nping -l flags
complete -c nping -l win
complete -c nping -l badsum
complete -c nping -l icmp-type
complete -c nping -l icmp-code
complete -c nping -l icmp-id
complete -c nping -l icmp-seq
complete -c nping -l icmp-redirect-addr
complete -c nping -l icmp-param-pointer
complete -c nping -l icmp-advert-lifetime
complete -c nping -l icmp-advert-entry
complete -c nping -l icmp-orig-time
complete -c nping -l icmp-recv-time
complete -c nping -l icmp-trans-time
complete -c nping -l arp-type
complete -c nping -l arp-sender-mac
complete -c nping -l arp-sender-ip
complete -c nping -l arp-target-mac
complete -c nping -l arp-target-ip
complete -c nping -s S -l source-ip
complete -c nping -l dest-ip
complete -c nping -l tos
complete -c nping -l id
complete -c nping -l df
complete -c nping -l mf
complete -c nping -l evil
complete -c nping -l ttl
complete -c nping -l badsum-ip
complete -c nping -l ip-options -l ip-options
complete -c nping -l mtu
complete -c nping -s 6 -l ipv6
complete -c nping -l flow
complete -c nping -l traffic-class
complete -c nping -l hop-limit -d 'Sets the IPv6 Hop Limit field in sent packets to the given value'
complete -c nping -l dest-mac
complete -c nping -l source-mac
complete -c nping -l ether-type
complete -c nping -l data
complete -c nping -l data-string
complete -c nping -l data-length
complete -c nping -l ec -l echo-client
complete -c nping -l es -l echo-server
complete -c nping -l no-crypto
complete -c nping -l ep -l echo-port
complete -c nping -l nc
complete -c nping -l once
complete -c nping -l safe-payloads
complete -c nping -l rate
complete -c nping -s h -l help
complete -c nping -s V -l version
complete -c nping -l count
complete -c nping -s e -l interface
complete -c nping -l privileged
complete -c nping -l unprivileged
complete -c nping -l send-eth
complete -c nping -l send-ip
complete -c nping -l bpf-filter -l filter
complete -c nping -s H -l hide-sent
complete -c nping -s N -l no-capture
complete -c nping -s v -l verbose
complete -c nping -s q -d 'decrements the verbosity level by one'
complete -c nping -o v3 -d or
complete -c nping -o v-1
complete -c nping -l reduce-verbosity
complete -c nping -s d
complete -c nping -o d4

