# pace
# Autogenerated from man page /usr/share/man/man1/pace.1.gz
complete -c pace -s h -l help -d 'Print help and exit'
complete -c pace -l up
complete -c pace -l down
complete -c pace -l first
complete -c pace -l last
complete -c pace -l above -d 'Move the given repository above OTHER_REPOSITORY'
complete -c pace -l below -d 'Move the given repository below OTHER_REPOSITORY.  add  NAME Add a repository'
complete -c pace -l server -d 'Add a Server key with URL value to the added repository'
complete -c pace -l include -d 'Add a Include key with PATH value to the added repository'
complete -c pace -l siglevel -d 'Add a SigLevel key with SIGLEVEL value to the added repository'
complete -c pace -l usage -d 'Add a Usage key with USAGE value to the added repository'
complete -c pace -l disabled -d 'Add the repository disabled'
complete -c pace -l version -d 'Print version and exit.  AUTHORS AndrÃ©s FernÃ¡ndez <andres@softwareperonista'

