# paclist
# Autogenerated from man page /usr/share/man/man8/paclist.8.gz
complete -c paclist -s h -l help -d 'Display syntax and command-line options'
complete -c paclist -s V -l version -d 'Display version information'

