# paclog-pkglist
# Autogenerated from man page /usr/share/man/man8/paclog-pkglist.8.gz
complete -c paclog-pkglist -s h -l help -d 'Display syntax and command-line options'
complete -c paclog-pkglist -s V -l version -d 'Display version information'

