# pacscripts
# Autogenerated from man page /usr/share/man/man8/pacscripts.8.gz
complete -c pacscripts -s h -l help -d 'Display syntax and command-line options'
complete -c pacscripts -s V -l version -d 'Display version information'

