# pacsearch
# Autogenerated from man page /usr/share/man/man8/pacsearch.8.gz
complete -c pacsearch -s n -l nocolor -d 'Do no colorize output'
complete -c pacsearch -s h -l help -d 'Display syntax and command-line options'
complete -c pacsearch -s V -l version -d 'Display version information'

