# pdiff
# Autogenerated from man page /usr/share/man/man1/pdiff.1.gz
complete -c pdiff -s h -l help -d 'display this help and exit'
complete -c pdiff -s v -l version -d 'display version information and exit'
complete -c pdiff -s q -l quiet -d 'don\'t print informational messages'
complete -c pdiff -s l -l lines -d 'search for line differences (`diff\')'
complete -c pdiff -s w -l words -d 'search for word differences (`wdiff\')'
complete -c pdiff -s o -l output -d 'save the output in FILE '

