# pki---acert
# Autogenerated from man page /usr/share/man/man1/pki---acert.1.gz
complete -c pki---acert -s h -l help -d 'Print usage information with a summary of the available options'
complete -c pki---acert -s v -l debug -d 'Set debug level, default: 1'
complete -c pki---acert -s + -l options -d 'Read command line options from file'
complete -c pki---acert -s i -l in -d 'Holder certificate to issue an attribute certificate for'
complete -c pki---acert -s m -l group -d 'Group membership the attribute certificate shall certify'
complete -c pki---acert -s k -l issuerkey -d 'Issuer private key file.  Either this or  --issuerkeyid is required'
complete -c pki---acert -s x -l issuerkeyid -d 'Smartcard or TPM issuer private key object handle in hex format with an optio…'
complete -c pki---acert -s c -l issuercert -d 'Issuer certificate file.  Required'
complete -c pki---acert -s l -l lifetime -d 'Hours the attribute certificate is valid, default: 24'
complete -c pki---acert -s F -l not-before -d 'Absolute time when the validity of the AC begins'
complete -c pki---acert -s T -l not-after -d 'Absolute time when the validity of the AC ends'
complete -c pki---acert -s D -l dateform -d 'strptime(3) format for the  --not-before and  --not-after options, default:  …'
complete -c pki---acert -s s -l serial -d 'Serial number in hex.  It is randomly allocated by default'
complete -c pki---acert -s g -l digest -d 'Digest to use for signature creation'
complete -c pki---acert -s R -l rsa-padding -d 'Padding to use for RSA signatures.  Either pkcs1 or pss, defaults to pkcs1'

