# pki---print
# Autogenerated from man page /usr/share/man/man1/pki---print.1.gz
complete -c pki---print -s h -l help -d 'Print usage information with a summary of the available options'
complete -c pki---print -s v -l debug -d 'Set debug level, default: 1'
complete -c pki---print -s + -l options -d 'Read command line options from file'
complete -c pki---print -s i -l in -d 'Input file.  If not given the input is read from STDIN'
complete -c pki---print -s x -l keyid -d 'Smartcard or TPM private key or certificate object handle in hex format with …'

