# pki---req
# Autogenerated from man page /usr/share/man/man1/pki---req.1.gz
complete -c pki---req -s h -l help -d 'Print usage information with a summary of the available options'
complete -c pki---req -s v -l debug -d 'Set debug level, default: 1'
complete -c pki---req -s + -l options -d 'Read command line options from file'
complete -c pki---req -s i -l in -d 'Private key input file.  If not given the key is read from STDIN'
complete -c pki---req -s x -l keyid -d 'Smartcard or TPM private key object handle in hex format with an optional 0x …'
complete -c pki---req -s t -l type -d 'Type of the input key.  Either priv, rsa, ecdsa or bliss, defaults to priv'
complete -c pki---req -s d -l dn -d 'Subject distinguished name (DN).  Required if the  --dn option is not set'
complete -c pki---req -s a -l san -d 'subjectAltName extension to include in request.  Can be used multiple times'
complete -c pki---req -s P -l profile -d 'Certificate profile name to be included in the certificate request'
complete -c pki---req -s e -l flag -d 'Add extendedKeyUsage flag'
complete -c pki---req -s p -l password -d 'The challengePassword to include in the certificate request'
complete -c pki---req -s o -l oldreq -d 'Old certificate request to be used as a template'
complete -c pki---req -s g -l digest -d 'Digest to use for signature creation'
complete -c pki---req -s R -l rsa-padding -d 'Padding to use for RSA signatures.  Either pkcs1 or pss, defaults to pkcs1'

