# pki---pkcs7
# Autogenerated from man page /usr/share/man/man1/pki---pkcs7.1.gz
complete -c pki---pkcs7 -s h -l help -d 'Print usage information with a summary of the available options'
complete -c pki---pkcs7 -s v -l debug -d 'Set debug level, default: 1'
complete -c pki---pkcs7 -s + -l options -d 'Read command line options from file'
complete -c pki---pkcs7 -s s -l sign -d 'Create PKCS#7 signed-data'
complete -c pki---pkcs7 -s u -l verify -d 'Verify PKCS#7 signed-data'
complete -c pki---pkcs7 -s e -l encrypt -d 'Create PKCS#7 enveloped-data'
complete -c pki---pkcs7 -l decrypt -d 'Decrypt PKCS#7 enveloped-data'
complete -c pki---pkcs7 -s p -l show -d 'Show information about PKCS#7 container, list certificates'
complete -c pki---pkcs7 -s i -l in -d 'PKCS#7 input file.  If not given the input is read from STDIN'
complete -c pki---pkcs7 -s k -l key -d 'Private key used for  --sign and  --decrypt'
complete -c pki---pkcs7 -s c -l cert -d 'Certificate for  --sign ,  --verify and  --encrypt'
complete -c pki---pkcs7 -s g -l digest -d 'Digest to use for signature creation'

