# pki---pub
# Autogenerated from man page /usr/share/man/man1/pki---pub.1.gz
complete -c pki---pub -s h -l help -d 'Print usage information with a summary of the available options'
complete -c pki---pub -s v -l debug -d 'Set debug level, default: 1'
complete -c pki---pub -s + -l options -d 'Read command line options from file'
complete -c pki---pub -s i -l in -d 'Input file.  If not given the input is read from STDIN'
complete -c pki---pub -s x -l keyid -d 'Smartcard or TPM private key object handle in hex format with an optional 0x …'
complete -c pki---pub -s t -l type -d 'Type of input'

