# pki---est
# Autogenerated from man page /usr/share/man/man1/pki---est.1.gz
complete -c pki---est -s h -l help -d 'Print usage information with a summary of the available options'
complete -c pki---est -s v -l debug -d 'Set debug level, default: 1'
complete -c pki---est -s + -l options -d 'Read command line options from file'
complete -c pki---est -s u -l url -d 'URL of the EST server'
complete -c pki---est -s l -l label -d 'Label in the EST server path'
complete -c pki---est -s i -l in -d 'PKCS#10 certificate request'
complete -c pki---est -s C -l cacert -d 'CA certificate in the trust chain used for EST TLS server signature verificat…'
complete -c pki---est -s c -l cert -d 'Client certificate to be renewed'
complete -c pki---est -s X -l certid -d 'Smartcard or TPM 2. 0 client certificate object handle'
complete -c pki---est -s k -l key -d 'Client private key to be replaced'
complete -c pki---est -s x -l keyid -d 'Smartcard or TPM 2. 0 client private key object handle'
complete -c pki---est -s p -l userpass -d 'Optional username:password that may be used for HTTP basic authentication'
complete -c pki---est -s t -l interval -d 'Poll interval in seconds, defaults to 60s'
complete -c pki---est -s m -l maxpolltime -d 'Maximum poll time in seconds, defaults to 0 which means unlimited polling'

