# pki---keyid
# Autogenerated from man page /usr/share/man/man1/pki---keyid.1.gz
complete -c pki---keyid -s h -l help -d 'Print usage information with a summary of the available options'
complete -c pki---keyid -s v -l debug -d 'Set debug level, default: 1'
complete -c pki---keyid -s + -l options -d 'Read command line options from file'
complete -c pki---keyid -s i -l in -d 'Input file.  If not given the input is read from STDIN'
complete -c pki---keyid -s x -l keyid -d 'Smartcard or TPM private key object handle in hex format with an optional 0x …'
complete -c pki---keyid -s t -l type -d 'Type of input'
complete -c pki---keyid -s I -l id -d 'Type of identifier'

