# pki---scepca
# Autogenerated from man page /usr/share/man/man1/pki---scepca.1.gz
complete -c pki---scepca -s h -l help -d 'Print usage information with a summary of the available options'
complete -c pki---scepca -s v -l debug -d 'Set debug level, default: 1'
complete -c pki---scepca -s + -l options -d 'Read command line options from file'
complete -c pki---scepca -s u -l url -d 'URL of the SCEP server'
complete -c pki---scepca -s c -l caout -d 'If present, path where the fetched root CA certificate file is stored to'
complete -c pki---scepca -s r -l raout -d 'If present, path where the fetched RA certificate file is stored to'
complete -c pki---scepca -s f -l outform -d 'Encoding of the created certificate file.  Either der (ASN'

