# pki---gen
# Autogenerated from man page /usr/share/man/man1/pki---gen.1.gz
complete -c pki---gen -s h -l help -d 'Print usage information with a summary of the available options'
complete -c pki---gen -s v -l debug -d 'Set debug level, default: 1'
complete -c pki---gen -s + -l options -d 'Read command line options from file'
complete -c pki---gen -s t -l type -d 'Type of key to generate'
complete -c pki---gen -s s -l size -d 'Key length in bits.  Defaults to 2048 for rsa and 384 for ecdsa'
complete -c pki---gen -s p -l safe-primes -d 'Generate RSA safe primes'
complete -c pki---gen -s f -l outform -d 'Encoding of the generated private key.  Either der (ASN'
complete -c pki---gen -s n -l shares -d 'Number of private RSA key shares'

