# pki---dn
# Autogenerated from man page /usr/share/man/man1/pki---dn.1.gz
complete -c pki---dn -s h -l help -d 'Print usage information with a summary of the available options'
complete -c pki---dn -s v -l debug -d 'Set debug level, default: 1'
complete -c pki---dn -s + -l options -d 'Read command line options from file'
complete -c pki---dn -s i -l in -d 'Input file.  If not given the input is read from STDIN'

