# pki---verify
# Autogenerated from man page /usr/share/man/man1/pki---verify.1.gz
complete -c pki---verify -s h -l help -d 'Print usage information with a summary of the available options'
complete -c pki---verify -s v -l debug -d 'Set debug level, default: 1'
complete -c pki---verify -s + -l options -d 'Read command line options from file'
complete -c pki---verify -s i -l in -d 'X. 509 certificate to verify.  If not given it is read from STDIN'
complete -c pki---verify -s c -l cacert -d 'CA certificate to use for trustchain verification'
complete -c pki---verify -s l -l crl -d 'Local CRL to use for trustchain verification'

