# pki---estca
# Autogenerated from man page /usr/share/man/man1/pki---estca.1.gz
complete -c pki---estca -s h -l help -d 'Print usage information with a summary of the available options'
complete -c pki---estca -s v -l debug -d 'Set debug level, default: 1'
complete -c pki---estca -s + -l options -d 'Read command line options from file'
complete -c pki---estca -s u -l url -d 'URL of the SCEP server'
complete -c pki---estca -s l -l label -d 'Label in the EST server path'
complete -c pki---estca -s C -l cacert -d 'CA certificate in the trust chain used for EST TLS server signature verificat…'
complete -c pki---estca -s c -l caout -d 'If present, path where the fetched root CA certificate file is stored to'
complete -c pki---estca -s f -l outform -d 'Encoding of the created certificate file.  Either der (ASN'

