# powertop
# Autogenerated from man page /usr/share/man/man8/powertop.8.gz
complete -c powertop -l auto-tune -d 'Set all tunable options to their good setting without interaction'
complete -c powertop -s c -l calibrate -d 'Runs powertop in calibration mode'
complete -c powertop -s C -l csv -d 'Generate a CSV report'
complete -c powertop -l debug -d 'Run in debug mode'
complete -c powertop -l extech -d 'Use the Extech Power Analyzer for measurements'
complete -c powertop -s r -l html -d 'Generate an HTML report'
complete -c powertop -s i -l iteration -d 'Number of times to run each test'
complete -c powertop -s q -l quiet -d 'Suppress stderr output'
complete -c powertop -s t -l time -d 'Generate a report for a specified number of R seconds '
complete -c powertop -s w -l workload -d 'Execute  workload file as a part of calibration before making a report'
complete -c powertop -s V -l version -d 'Print version information and exit'
complete -c powertop -s h -l help -d 'Show the help message and exit'

