# psbook
# Autogenerated from man page /usr/share/man/man1/psbook.1.gz
complete -c psbook -s s -l signature -d 'number of pages per signature; 0 = all pages in one signature [default]; 1 = …'
complete -c psbook -s q -l quiet -d 'don\'t show page numbers being output'
complete -c psbook -l help -d 'display this help and exit'
complete -c psbook -s v -l version -d 'display version information and exit '

