# psjoin
# Autogenerated from man page /usr/share/man/man1/psjoin.1.gz
complete -c psjoin -s e -l even -d 'force each file to an even number of pages'
complete -c psjoin -s s -l save -d 'try to close unclosed save operators'
complete -c psjoin -s n -l nostrip -d 'do not strip prolog or trailer from input files'
complete -c psjoin -l help -d 'display this help and exit'
complete -c psjoin -s v -l version -d 'display version information and exit . SS "Exit status:"'

