# psnup
# Autogenerated from man page /usr/share/man/man1/psnup.1.gz
complete -c psnup -o NUMBER -d 'number of pages to impose on each output page'
complete -c psnup -s p -l paper -d 'output paper name or dimensions'
complete -c psnup -s P -l inpaper -d 'input paper name or dimensions'
complete -c psnup -s m -l margin -d 'width of margin around each output page [default 0pt]; useful for thumbnail s…'
complete -c psnup -s b -l border -d 'width of border around each input page'
complete -c psnup -s d -l draw -d 'draw a line of given width around each page [relative to input page size; arg…'
complete -c psnup -s l -l rotatedleft -d 'input pages are rotated left 90 degrees'
complete -c psnup -s r -l rotatedright -d 'input pages are rotated right 90 degrees'
complete -c psnup -s f -l flip -d 'swap output pages\' width and height'
complete -c psnup -s c -l transpose -d 'swap columns and rows (column-major order)'
complete -c psnup -s t -l tolerance -d 'maximum wasted area in square pt [default: 100,000]'
complete -c psnup -s q -l quiet -d 'don\'t show page numbers being output'
complete -c psnup -l help -d 'display this help and exit'
complete -c psnup -s v -l version -d 'display version information and exit '

