# psresize
# Autogenerated from man page /usr/share/man/man1/psresize.1.gz
complete -c psresize -s p -l paper -d 'output paper size'
complete -c psresize -s P -l inpaper -d 'input paper size'
complete -c psresize -s q -l quiet -d 'don\'t show page numbers being output'
complete -c psresize -l help -d 'display this help and exit'
complete -c psresize -s v -l version -d 'display version information and exit '

