# psselect
# Autogenerated from man page /usr/share/man/man1/psselect.1.gz
complete -c psselect -s R -s p -l pages -d 'select the given page ranges'
complete -c psselect -s e -l even -d 'select even-numbered pages'
complete -c psselect -s o -l odd -d 'select odd-numbered pages'
complete -c psselect -s r -l reverse -d 'reverse the order of the pages'
complete -c psselect -s q -l quiet -d 'don\'t show page numbers being output'
complete -c psselect -l help -d 'display this help and exit'
complete -c psselect -s v -l version -d 'display version information and exit '

