# pstops
# Autogenerated from man page /usr/share/man/man1/pstops.1.gz
complete -c pstops -s S -l specs -d 'page specifications (see below)'
complete -c pstops -s R -l pages -d 'select the given page ranges'
complete -c pstops -s e -l even -d 'select even-numbered output pages'
complete -c pstops -s o -l odd -d 'select odd-numbered output pages'
complete -c pstops -s r -l reverse -d 'reverse the order of the output pages'
complete -c pstops -s p -l paper -d 'output paper name or dimensions (WIDTHxHEIGHT)'
complete -c pstops -s P -l inpaper -d 'input paper name or dimensions (WIDTHxHEIGHT)'
complete -c pstops -s d -l draw -d 'draw a line of given width (relative to original page) around each page [argu…'
complete -c pstops -s b -l nobind -d 'disable PostScript bind operators in prolog; may be needed for complex page r…'
complete -c pstops -s q -l quiet -d 'don\'t show page numbers being output'
complete -c pstops -l help -d 'display this help and exit'
complete -c pstops -s v -l version -d 'display version information and exit '

