# qbittorrent
# Autogenerated from man page /usr/share/man/man1/qbittorrent.1.gz
complete -c qbittorrent -l help
complete -c qbittorrent -l version -d number
complete -c qbittorrent -l no-splash
complete -c qbittorrent -l webui-port -d '8080)'

