# qpdf
# Autogenerated from man page /usr/share/man/man1/qpdf.1.gz
complete -c qpdf -l empty -d 'Use in place of infile for an empty input.  Especially useful with --pages'
complete -c qpdf -l replace-input -d 'Use in place of outfile to overwrite the input file with the output'
complete -c qpdf -l job-json-file
complete -c qpdf -l warning-exit-0 -d 'Use exit status 0 instead of 3 when warnings are present'
complete -c qpdf -l completion-bash -d 'Output a command that enables bash completion'
complete -c qpdf -l completion-zsh -d 'Output a command that enables zsh completion HELP (information about qpdf) He…'
complete -c qpdf -l help
complete -c qpdf -l option
complete -c qpdf -l version -d 'Display the version of qpdf'
complete -c qpdf -l copyright -d 'Display copyright and license information'
complete -c qpdf -l show-crypto -d 'Show a list of available crypto providers, one per line'
complete -c qpdf -l job-json-help -d 'Describe the format of the QPDFJob JSON input used by'
complete -c qpdf -l password
complete -c qpdf -l password-file
complete -c qpdf -l verbose -d 'Output additional information about various things qpdf is doing, including i…'
complete -c qpdf -l progress -d 'Indicate progress when writing files'
complete -c qpdf -l no-warn -d 'Suppress printing of warning messages'
complete -c qpdf -l deterministic-id -d 'Generate a secure, random document ID only using static information, such as …'
complete -c qpdf -l allow-weak-crypto -d 'Allow creation of files with weak cryptographic algorithms'
complete -c qpdf -l keep-files-open
complete -c qpdf -l keep-files-open-threshold
complete -c qpdf -l password-is-hex-key -d 'Provide the underlying file encryption key as a hex-encoded string rather tha…'
complete -c qpdf -l suppress-password-recovery -d 'Suppress qpdf\'s usual behavior of attempting different encodings of a passwor…'
complete -c qpdf -l password-mode
complete -c qpdf -l suppress-recovery -d 'Avoid attempting to recover when errors are found in a file\'s cross reference…'
complete -c qpdf -l ignore-xref-streams -d 'Ignore any cross-reference streams in the file, falling back to cross-referen…'
complete -c qpdf -l linearize -d 'Create linearized (web-optimized) output files'
complete -c qpdf -l encrypt
complete -c qpdf -l decrypt -d 'Create an unencrypted output file even if the input file was encrypted'
complete -c qpdf -l remove-restrictions -d 'Remove restrictions associated with digitally signed PDF files'
complete -c qpdf -l copy-encryption
complete -c qpdf -l encryption-file-password
complete -c qpdf -l qdf -d 'Create a PDF file suitable for viewing in a text editor and even editing'
complete -c qpdf -l no-original-object-ids -d 'Omit comments in a QDF file indicating the object ID an object had in the ori…'
complete -c qpdf -l compress-streams
complete -c qpdf -l decode-level
complete -c qpdf -l json-output -d '[bu] generalized: uncompress streams compressed with a general-purpose compre…'
complete -c qpdf -l stream-data
complete -c qpdf -l recompress-flate -d 'The default generalized compression scheme used by PDF is flate, which is the…'
complete -c qpdf -l compression-level
complete -c qpdf -l normalize-content
complete -c qpdf -l object-streams
complete -c qpdf -l preserve-unreferenced -d 'Preserve all objects from the input even if not referenced'
complete -c qpdf -l remove-unreferenced-resources
complete -c qpdf -l preserve-unreferenced-resources -d 'Synonym for --remove-unreferenced-resources=no.  Use that instead'
complete -c qpdf -l newline-before-endstream -d 'For an extra newline before endstream'
complete -c qpdf -l coalesce-contents -d 'If a page has an array of content streams, concatenate them into a single con…'
complete -c qpdf -l externalize-inline-images -d 'Convert inline images to regular images'
complete -c qpdf -l ii-min-bytes
complete -c qpdf -l min-version
complete -c qpdf -l force-version
complete -c qpdf -l pages
complete -c qpdf -l collate
complete -c qpdf -l split-pages
complete -c qpdf -l overlay
complete -c qpdf -l underlay
complete -c qpdf -l flatten-rotation -d 'For each page that is rotated using the /Rotate key in the page\'s dictionary,…'
complete -c qpdf -l flatten-annotations
complete -c qpdf -l rotate
complete -c qpdf -o ']angle'
complete -c qpdf -l generate-appearances -d 'PDF form fields consist of values and appearances, which may be inconsistent …'
complete -c qpdf -l optimize-images -d 'Attempt to use DCT (JPEG) compression for images that fall within certain con…'
complete -c qpdf -l oi-min-width
complete -c qpdf -l oi-min-height
complete -c qpdf -l oi-min-area
complete -c qpdf -l keep-inline-images -d 'Prevent inline images from being considered by --optimize-images'
complete -c qpdf -l remove-page-labels -d 'Exclude page labels (explicit page numbers) from the output file'
complete -c qpdf -l user-password
complete -c qpdf -l owner-password
complete -c qpdf -l bits
complete -c qpdf -l accessibility
complete -c qpdf -l annotate
complete -c qpdf -l assemble
complete -c qpdf -l extract
complete -c qpdf -l form
complete -c qpdf -l modify-other
complete -c qpdf -l modify
complete -c qpdf -l print
complete -c qpdf -l cleartext-metadata -d 'If specified, don\'t encrypt document metadata even when encrypting the rest o…'
complete -c qpdf -l use-aes
complete -c qpdf -l allow-insecure -d 'Allow creation of PDF files with empty owner passwords and non-empty user pas…'
complete -c qpdf -l force-V4 -d 'This option is for testing and is never needed in practice since qpdf does th…'
complete -c qpdf -l force-R5 -d 'Use an undocumented, unsupported, deprecated encryption algorithm that existe…'
complete -c qpdf -l to
complete -c qpdf -l from
complete -c qpdf -l repeat
complete -c qpdf -l list-attachments -l show-attachment
complete -c qpdf -l add-attachment
complete -c qpdf -l copy-attachments-from
complete -c qpdf -l remove-attachment
complete -c qpdf -l key
complete -c qpdf -l filename
complete -c qpdf -l creationdate
complete -c qpdf -l moddate
complete -c qpdf -l mimetype
complete -c qpdf -l description
complete -c qpdf -l replace -d 'Indicate that any existing attachment with the same key should be replaced by…'
complete -c qpdf -l prefix
complete -c qpdf -l is-encrypted -d 'Silently exit with a code indicating the file\'s encryption status:'
complete -c qpdf -l requires-password -d 'Silently exit with a code indicating the file\'s password status:'
complete -c qpdf -l check -d 'Check the structure of the PDF file as well as a number of other aspects of t…'
complete -c qpdf -l show-encryption -d 'Show document encryption parameters'
complete -c qpdf -l show-encryption-key -d 'When used with --show-encryption or --check, causes the underlying encryption…'
complete -c qpdf -l check-linearization -d 'Check to see whether a file is linearized and, if so, whether the linearizati…'
complete -c qpdf -l show-linearization -d 'Check and display all data in the linearization hint tables'
complete -c qpdf -l show-xref -d 'Show the contents of the cross-reference table or stream (object locations in…'
complete -c qpdf -l show-object
complete -c qpdf -l raw-stream-data -d 'When used with --show-object, if the object is a stream, write the raw (compr…'
complete -c qpdf -l filtered-stream-data
complete -c qpdf -l show-npages -d 'Print the number of pages in the input file on a line by itself'
complete -c qpdf -l show-pages -d 'Show the object and generation number for each page dictionary object and for…'
complete -c qpdf -l with-images -d 'When used with --show-pages, also shows the object and generation numbers for…'
complete -c qpdf -l json
complete -c qpdf -l json-help
complete -c qpdf -l json-key
complete -c qpdf -l json-object
complete -c qpdf -l json-stream-data
complete -c qpdf -l json-stream-prefix -d 'when --json-output is specified, in which case the default is "inline"'
complete -c qpdf -l json-input -d 'Treat the input file as a JSON file in qpdf JSON format'
complete -c qpdf -l update-from-json
complete -c qpdf -l static-id -d 'Use a fixed value for the document ID.  This is intended for testing only'
complete -c qpdf -l static-aes-iv -d 'Use a static initialization vector for AES-CBC'
complete -c qpdf -l linearize-pass1
complete -c qpdf -l test-json-schema -d 'This is used by qpdf\'s test suite to check consistency between the output of …'
complete -c qpdf -l report-memory-usage -d 'This is used by qpdf\'s performance test suite to report the maximum amount of…'

