# radvdump
# Autogenerated from man page /usr/share/man/man8/radvdump.8.gz
complete -c radvdump -s v -l version -d 'Displays the version of  radvdump and then aborts'
complete -c radvdump -s h -l help -d 'Displays a short usage description and then aborts'
complete -c radvdump -s f -l file-format -d 'Output received router advertisements in the format of the  radvd configurati…'
complete -c radvdump -s e -l exclude-defaults -d 'Exclude default valued options from configuration file format'
complete -c radvdump -s d -l debug -d 'With this option you turn on debugging information'

