# radvd
# Autogenerated from man page /usr/share/man/man8/radvd.8.gz
complete -c radvd -s v -l version -d 'Displays the version of  radvd and then aborts'
complete -c radvd -s h -l help -d 'Displays a short usage description and then aborts'
complete -c radvd -s c -l configtest -d 'Test configuration and do startup tests and then exit'
complete -c radvd -s n -l nodaemon -d 'Prevent the daemonizing'
complete -c radvd -s d -l debug -d 'With this option you turn on debugging information'
complete -c radvd -s C -l config -d 'Specifies an alternate config file'
complete -c radvd -s p -l pidfile -d 'Specifies an alternate pidfile.  Normally the compiled in default  /run/radvd'
complete -c radvd -s m -l logmethod -d 'Specifies the logging method to use.  Possibly values are: . RS'
complete -c radvd -s l -l logfile -d 'Specifies the logfile to use when using the logging method R logfile '
complete -c radvd -s f -l facility -d 'Specifies the facility (as an integer) when using syslog logging'
complete -c radvd -s t -l chrootdir -d 'If specified, switches to   chrootdir before doing anything else'
complete -c radvd -s u -d 'must always be used when using chrootdir '
complete -c radvd -l username -d 'If specified, drops root privileges and changes user ID to username and group…'
complete -c radvd -o writable -d 'FILES /usr/bin/radvd /etc/radvd. conf /run/radvd. pid /var/log/radvd. log'

