# rankmirrors
# Autogenerated from man page /usr/share/man/man8/rankmirrors.8.gz
complete -c rankmirrors -s n -d 'Number of servers to output, 0 for all'
complete -c rankmirrors -s m -l max-time -d 'Specify a ranking operation timeout, can be decimal number'
complete -c rankmirrors -s p -l parallel -d 'Run tests in parallel for all servers (may be inaccurate, depends on GNU para…'
complete -c rankmirrors -s r -l repo -d 'Specify a repository name instead of guessing'
complete -c rankmirrors -l times -d 'Only output mirrors and their response times'
complete -c rankmirrors -s u -l url -d 'Test a specific URL'
complete -c rankmirrors -s v -l verbose -d 'Be verbose in output'
complete -c rankmirrors -s h -l help -d 'Display syntax and command-line options'
complete -c rankmirrors -s V -l version -d 'Display version information'

