# remote-viewer
# Autogenerated from man page /usr/share/man/man1/remote-viewer.1.gz
complete -c remote-viewer -s h -l help -d 'Display command line help summary'
complete -c remote-viewer -s V -l version -d 'Display program version number'
complete -c remote-viewer -s v -l verbose -d 'Display information about the connection'
complete -c remote-viewer -s z -l zoom -d 'Zoom level of the display window in percentage.  Range 10-400'
complete -c remote-viewer -s f -l full-screen -d 'Start with the windows maximized to fullscreen'
complete -c remote-viewer -l auto-resize -d 'Controls whether it is permitted to attempt to resize the remote framebuffer …'
complete -c remote-viewer -s t -l title -d 'Set the window title to \\s-1TITLE\\s0'
complete -c remote-viewer -s s -l shared -d 'Permitted a shared session with multiple clients'
complete -c remote-viewer -l cursor -d 'Control how the mouse cursor is rendered'
complete -c remote-viewer -l debug -d 'Print debugging information'
complete -c remote-viewer -s H -l hotkeys -d 'Set global hotkey bindings'
complete -c remote-viewer -s K -l keymap -d 'Remap and/or block supplied keypresses to the host'
complete -c remote-viewer -s k -l kiosk -d 'Start in kiosk mode'

