# rpc.rquotad
# Autogenerated from man page /usr/share/man/man8/rpc.rquotad.8.gz
complete -c 'rpc.rquotad' -s h -l help -d 'Show program usage and exit.   -V, --version Show version of quota tools'
complete -c 'rpc.rquotad' -s s -l no-setquota -d 'Don\'t allow setting of quotas (default)'
complete -c 'rpc.rquotad' -s S -l setquota -d 'Allow setting of quotas'
complete -c 'rpc.rquotad' -s F -l foreground -d 'Run daemon in foreground (may be useful for debugging purposes)'
complete -c 'rpc.rquotad' -s I -l autofs -d 'Do not ignore autofs mountpoints'
complete -c 'rpc.rquotad' -s p -l port -d 'Listen on alternate port R port'
complete -c 'rpc.rquotad' -s V -l version -d 'Show version of quota tools'
complete -c 'rpc.rquotad' -s x -l xtab -d 'Set an alternative file with NFSD export table'

