# samba-dcerpcd
# Autogenerated from man page /usr/share/man/man8/samba-dcerpcd.8.gz
complete -c samba-dcerpcd -s D -l daemon -d 'If specified, this parameter causes the server to operate as a daemon'
complete -c samba-dcerpcd -s i -l interactive -d 'If this parameter is specified it causes the server to run "interactively", n…'
complete -c samba-dcerpcd -s F -l foreground -d 'If specified, this parameter causes the main samba-dcerpcd process to not dae…'
complete -c samba-dcerpcd -l no-process-group -d 'Do not create a new process group for samba-dcerpcd'
complete -c samba-dcerpcd -l libexec-rpcds -d 'Offer RPC services for all daemons in Samba\\*(Aqs LIBEXECDIR, all programs st…'
complete -c samba-dcerpcd -l np-helper -d 'Run samba-dcerpcd on demand opening named pipe sockets as helpers for smbd or…'
complete -c samba-dcerpcd -l ready-signal-fd -d 'Report service readiness via this fd to smbd.  Only for internal use'
complete -c samba-dcerpcd -s S -d 'parameter had been given'

