# samba-tool
# Autogenerated from man page /usr/share/man/man8/samba-tool.8.gz
complete -c samba-tool -s h -l help -d 'Show this help message and exit'
complete -c samba-tool -s r -l realm -d 'Set the realm for the domain'
complete -c samba-tool -l simple-bind-dn -d 'DN to use for a simple bind'
complete -c samba-tool -l password -d 'Specify the password on the commandline'
complete -c samba-tool -s U -l user -d 'Sets the SMB username or username and password'
complete -c samba-tool -s W -l workgroup -d 'Set the SMB domain of the username'
complete -c samba-tool -s N -l no-pass -d 'If specified, this parameter suppresses the normal password prompt from the c…'
complete -c samba-tool -l use-kerberos -d 'This parameter determines whether Samba client tools will try to authenticate…'
complete -c samba-tool -l use-krb5-ccache -d 'Specifies the credential cache location for Kerberos authentication'
complete -c samba-tool -s A -l authentication-file -d 'This option allows you to specify a file from which to read the username and …'
complete -c samba-tool -l ipaddress -d 'IP address of the server'
complete -c samba-tool -l color -d 'Indicate whether samba-tool should use ANSI colour codes in its output'
complete -c samba-tool -s d -l debuglevel -d 'level is an integer from 0 to 10'
complete -c samba-tool -l debug-stdout -d 'This will redirect debug output to STDOUT'
complete -c samba-tool -l computerou
complete -c samba-tool -l description
complete -c samba-tool -l ip-address
complete -c samba-tool -l service-principal-name
complete -c samba-tool -l prepare-oldjoin
complete -c samba-tool -l editor
complete -c samba-tool -l attributes
complete -c samba-tool -l ou
complete -c samba-tool -l surname
complete -c samba-tool -l given-name
complete -c samba-tool -l initials
complete -c samba-tool -l display-name
complete -c samba-tool -l job-title
complete -c samba-tool -l department
complete -c samba-tool -l company
complete -c samba-tool -l mail-address
complete -c samba-tool -l internet-address
complete -c samba-tool -l telephone-number
complete -c samba-tool -l mobile-number
complete -c samba-tool -l physical-delivery-office
complete -c samba-tool -l full-dn
complete -c samba-tool -l force-new-cn
complete -c samba-tool -l reset-cn
complete -c samba-tool -s H -l URL
complete -c samba-tool -l json
complete -c samba-tool -l name
complete -c samba-tool -l protect
complete -c samba-tool -l unprotect
complete -c samba-tool -l audit
complete -c samba-tool -l enforce
complete -c samba-tool -l strong-ntlm-policy
complete -c samba-tool -l user-tgt-lifetime
complete -c samba-tool -l user-allow-ntlm-auth
complete -c samba-tool -l service-tgt-lifetime
complete -c samba-tool -l service-allow-ntlm-auth
complete -c samba-tool -l computer-tgt-lifetime
complete -c samba-tool -l force
complete -c samba-tool -l policy
complete -c samba-tool -l user-policy
complete -c samba-tool -l service-policy
complete -c samba-tool -l computer-policy
complete -c samba-tool -l member
complete -c samba-tool -l attribute
complete -c samba-tool -l class
complete -c samba-tool -l enable
complete -c samba-tool -l disable
complete -c samba-tool -l hide-expired
complete -c samba-tool -l hide-disabled
complete -c samba-tool -l samaccountname
complete -c samba-tool -l use-ntvfs
complete -c samba-tool -l service
complete -c samba-tool -l use-s3fs
complete -c samba-tool -l xattr-backend
complete -c samba-tool -l eadb-file
complete -c samba-tool -l recursive
complete -c samba-tool -l follow-symlinks
complete -c samba-tool -l verbose
complete -c samba-tool -l force-subtree-delete
complete -c samba-tool -s b -l base-dn
complete -c samba-tool -l upn
complete -c samba-tool -l distance
complete -c samba-tool -l dot
complete -c samba-tool -l xdot

