# samba-gpupdate
# Autogenerated from man page /usr/share/man/man8/samba-gpupdate.8.gz
complete -c samba-gpupdate -s h
complete -c samba-gpupdate -l help -d 'show this help message and exit'
complete -c samba-gpupdate -s H
complete -c samba-gpupdate -l url -d 'URL for the samdb'
complete -c samba-gpupdate -s X
complete -c samba-gpupdate -l unapply -d 'Unapply Group Policy'
complete -c samba-gpupdate -l target -d '{Computer | User}'
complete -c samba-gpupdate -l force -d 'Reapplies all policy settings'
complete -c samba-gpupdate -l rsop -d 'Print the Resultant Set of Policy'
complete -c samba-gpupdate -s s
complete -c samba-gpupdate -l configfile -d 'Configuration file'
complete -c samba-gpupdate -s d
complete -c samba-gpupdate -l debuglevel -d 'debug level'
complete -c samba-gpupdate -l option -d 'set smb. conf option from command line'
complete -c samba-gpupdate -l realm -d 'set the realm name'
complete -c samba-gpupdate -s V
complete -c samba-gpupdate -l version -d 'Display version number'
complete -c samba-gpupdate -l simple-bind-dn -d 'DN to use for a simple bind'
complete -c samba-gpupdate -l password -d Password
complete -c samba-gpupdate -s U
complete -c samba-gpupdate -l username -d Username
complete -c samba-gpupdate -s W
complete -c samba-gpupdate -l workgroup -d Workgroup
complete -c samba-gpupdate -s N
complete -c samba-gpupdate -l no-pass -d 'Dont ask for a password'
complete -c samba-gpupdate -s k
complete -c samba-gpupdate -l kerberos -d 'Use Kerberos'
complete -c samba-gpupdate -l ipaddress -d 'IP address of server'
complete -c samba-gpupdate -s P
complete -c samba-gpupdate -l machine-pass -d 'Use stored machine account password AUTHOR'

