# samba-log-parser
# Autogenerated from man page /usr/share/man/man1/samba-log-parser.1.gz
complete -c samba-log-parser -l pid -d 'Display traces for winbind client with the matching PID'
complete -c samba-log-parser -l traceid -d 'Display traces with matching traceid debug header field'
complete -c samba-log-parser -l breakdown -d 'Break down all traces to separate files in the current working directory'
complete -c samba-log-parser -l merge-by-timestamp -d 'Sort the trace lines according to the timestamp'
complete -c samba-log-parser -l flow -d 'Display the request/sub-request flow'
complete -c samba-log-parser -l flow-compact -d 'Display the request/sub-request flow without dcerpc call details'

