# slapmodify
# Autogenerated from man page /usr/share/man/man8/slapmodify.8.gz
complete -c slapmodify -s b -d 'Use the specified suffix to determine which database to add entries to'
complete -c slapmodify -s c -d 'enable continue (ignore errors) mode'
complete -c slapmodify -s d -d 'enable debugging messages as defined by the specified R debug-level ; see  sl…'
complete -c slapmodify -s f -d 'specify an alternative  slapd. conf (5) file'
complete -c slapmodify -s F -d 'specify a config directory'
complete -c slapmodify -s g -d 'disable subordinate gluing'
complete -c slapmodify -s j -d 'Jump to the specified line number in the LDIF file before processing any entr…'
complete -c slapmodify -s l -d 'Read LDIF from the specified file instead of standard input'
complete -c slapmodify -s n -d 'Perform changes on the dbnum-th database listed in the configuration file'
complete -c slapmodify -s o -d 'Specify an  option with a(n optional) R value '
complete -c slapmodify -s q -d 'enable quick (fewer integrity checks) mode'
complete -c slapmodify -s s -d 'disable schema checking'
complete -c slapmodify -s S -d 'Server ID to use in generated entryCSN'
complete -c slapmodify -s u -d 'enable dry-run (don\'t write to backend) mode'
complete -c slapmodify -s v -d 'enable verbose mode'
complete -c slapmodify -s w -d 'write syncrepl context information'

