# snapper
# Autogenerated from man page /usr/share/man/man8/snapper.8.gz
complete -c snapper -s q -l quiet
complete -c snapper -s v -l verbose
complete -c snapper -l debug
complete -c snapper -l utc
complete -c snapper -l iso
complete -c snapper -s t -l table-style
complete -c snapper -l abbreviate
complete -c snapper -l machine-readable
complete -c snapper -l csvout
complete -c snapper -l jsonout
complete -c snapper -l separator
complete -c snapper -l no-headers
complete -c snapper -s c -l config
complete -c snapper -l no-dbus
complete -c snapper -s r -l root
complete -c snapper -s a -l ambit
complete -c snapper -l version
complete -c snapper -l columns
complete -c snapper -s f -l fstype
complete -c snapper -l template
complete -c snapper -l type
complete -c snapper -l disable-used-space
complete -c snapper -l all-configs
complete -c snapper -l pre-number
complete -c snapper -s p -l print-number
complete -c snapper -s d -l description
complete -c snapper -l cleanup-algorithm
complete -c snapper -s u -l userdata
complete -c snapper -l command
complete -c snapper -l read-only
complete -c snapper -l read-write
complete -c snapper -l from
complete -c snapper -l default
complete -c snapper -s s -l sync
complete -c snapper -s o -l output
complete -c snapper -s i -l input
complete -c snapper -l diff-cmd
complete -c snapper -s x -l extensions
complete -c snapper -l path
complete -c snapper -l free-space
complete -c snapper -o ':user.bar' -d 'for removed attributes oc o 2. 3'
complete -c snapper -o '+:security.selinux' -d 'for modified attributes PERMISSIONS'

