# sonic
# Autogenerated from man page /usr/share/man/man1/sonic.1.gz
complete -c sonic -s c -d 'Modify pitch by emulating vocal chords vibrating faster or slower'
complete -c sonic -s p -d 'Set pitch scaling factor.   1. 3 means 30%% higher'
complete -c sonic -s q -d 'Disable all speed-up heuristics, possibly improving the quality slightly'
complete -c sonic -s r -d 'Adjust the speed of playback.   This scales both the pitch and speed equally'
complete -c sonic -s s -d 'Set speed up factor.   1. 0 means no change, 2. 0 means 2X faster'
complete -c sonic -s v -d 'Scale volume by scaleFactor.   1. 5 increases by 50%'

