# spice-client
# Autogenerated from man page /usr/share/man/man1/spice-client.1.gz
complete -c spice-client -l spice-secure-channels -d 'Force the specified channels to be secured '
complete -c spice-client -l spice-disable-effects -d 'Disable guest display effects '
complete -c spice-client -l spice-color-depth -d 'Guest display color depth - \\s-1DEPRECATED\\s0 '
complete -c spice-client -l spice-ca-file -d 'Truststore file for secure connections . Sp This option is used to specify a '
complete -c spice-client -l spice-host-subject -d 'Subject of the host certificate (field=value pairs separated by commas) '
complete -c spice-client -l spice-debug -d 'Enable Spice-GTK debugging'
complete -c spice-client -l spice-disable-audio -d 'Disable audio support'
complete -c spice-client -l spice-disable-usbredir -d 'Disable \\s-1USB\\s0 redirection support'
complete -c spice-client -l spice-usbredir-auto-redirect-filter -d 'Filter selecting \\s-1USB\\s0 devices to be auto-redirected when plugged in '
complete -c spice-client -l spice-usbredir-redirect-on-connect -d 'Filter selecting \\s-1USB\\s0 devices to redirect on connect '
complete -c spice-client -l spice-gtk-version -d 'Display Spice-GTK version information'
complete -c spice-client -l spice-smartcard -d 'Enable smartcard support'
complete -c spice-client -l spice-smartcard-db -d 'Path to the local certificate database to use for software smartcard certific…'
complete -c spice-client -l spice-smartcard-certificates -d 'Certificates to use for software smartcards (field=values separated by commas…'
complete -c spice-client -l spice-cache-size -d 'Image cache size - \\s-1DEPRECATED\\s0 '

