# squashfuse
# Autogenerated from man page /usr/share/man/man1/squashfuse.1.gz
complete -c squashfuse -s o -d 'offset N bytes into archive to mount El -tag -width -indent'
complete -c squashfuse -s h -d 'print help'
complete -c squashfuse -s V -d 'show FUSE version'
complete -c squashfuse -s d -d 'enable debug output (implies f )'
complete -c squashfuse -s f -d 'foreground operation'

