# svnserve
# Autogenerated from man page /usr/share/man/man8/svnserve.8.gz
complete -c svnserve -s d -l daemon -d 'Causes svnserve to run in daemon mode'
complete -c svnserve -l listen-port -d 'Causes svnserve to listen on port when run in daemon mode'
complete -c svnserve -l listen-host -d 'Causes svnserve to listen on the interface specified by host, which may be ei…'
complete -c svnserve -l foreground -d 'When used together with -d, this option causes svnserve to stay in the foregr…'
complete -c svnserve -s i -l inetd -d 'Causes svnserve to use the stdin/stdout file descriptors, as is appropriate f…'
complete -c svnserve -s h -l help -d 'Displays a usage summary and exits'
complete -c svnserve -l version -d 'Print svnserve\'s version and the repository filesystem back-end(s) a particul…'
complete -c svnserve -s r -l root -d 'Sets the virtual root for repositories served by svnserve'
complete -c svnserve -s R -l read-only -d 'Force all write operations through this svnserve instance to be forbidden, ov…'
complete -c svnserve -s t -l tunnel -d 'Causes svnserve to run in tunnel mode, which is just like the inetd mode of o…'
complete -c svnserve -l tunnel-user -d 'When combined with --tunnel, overrides the pre-authenticated username with th…'
complete -c svnserve -s T -l threads -d 'When running in daemon mode, causes svnserve to spawn a thread instead of a p…'
complete -c svnserve -l config-file -d 'When specified, svnserve reads filename once at program startup and caches th…'
complete -c svnserve -l pid-file -d 'When specified, svnserve will write its process ID to filename'
complete -c svnserve -s X -l listen-once -d 'Causes svnserve to accept one connection on the svn port, serve it, and exit'

