# theme
# Autogenerated from man page /usr/share/man/man1/theme.1.gz
complete -c theme -s d -d 'Set the "document root" to root'
complete -c theme -s E -d 'Normally theme will not expand "<?theme body?>" or "<?theme toc?>" in the "<h…'
complete -c theme -s f -d 'Forcibly overwrite existing html files'
complete -c theme -s o -d 'Write the output to filename'
complete -c theme -s p -d 'Set the pagename to path'
complete -c theme -s t -d 'Use filename as the template file'

