# updpkgsums
# Autogenerated from man page /usr/share/man/man8/updpkgsums.8.gz
complete -c updpkgsums -s h -l help -d 'Display syntax and command-line options'
complete -c updpkgsums -s m -l nocolor -d 'Do not colorize output'
complete -c updpkgsums -s V -l version -d 'Display version information'

