# view
# Autogenerated from man page /usr/share/man/man1/view.1.gz
complete -c view -o ccommand -d 'Execute  command when editing begins'
complete -c view -s l -d 'Start in a special mode useful for the  Lisp programming language'
complete -c view -s r -s L -d 'When no argument is supplied with this option, all files to be recovered are …'
complete -c view -s R -d 'Files are opened read-only when this option is given'
complete -c view -s s -d 'Script mode; all feedback for interactive editing is disabled'
complete -c view -s t -d 'Read the  tags file, then choose the file and position specified by  tagstrin…'
complete -c view -s V -d 'Echo command input to standard error, unless it originates from a terminal'
complete -c view -s w -d 'Specify the size of the editing window for visual mode'
complete -c view -s c -d 'Execute command when editing begins'

