# virt-qemu-sev-validate
# Autogenerated from man page /usr/share/man/man1/virt-qemu-sev-validate.1.gz
complete -c virt-qemu-sev-validate -s h -l help
complete -c virt-qemu-sev-validate -s d -l debug
complete -c virt-qemu-sev-validate -s q -l quiet
complete -c virt-qemu-sev-validate -l measurement
complete -c virt-qemu-sev-validate -l api-major
complete -c virt-qemu-sev-validate -l api-minor
complete -c virt-qemu-sev-validate -l build-id
complete -c virt-qemu-sev-validate -l policy
complete -c virt-qemu-sev-validate -s f -l firmware
complete -c virt-qemu-sev-validate -s k -l kernel
complete -c virt-qemu-sev-validate -s r -l initrd
complete -c virt-qemu-sev-validate -s e -l cmdline
complete -c virt-qemu-sev-validate -s n -l num-cpus
complete -c virt-qemu-sev-validate -s 0 -l vmsa-cpu0
complete -c virt-qemu-sev-validate -s 1 -l vmsa-cpu1
complete -c virt-qemu-sev-validate -l tik
complete -c virt-qemu-sev-validate -l tek
complete -c virt-qemu-sev-validate -l tk
complete -c virt-qemu-sev-validate -s c -l connect
complete -c virt-qemu-sev-validate -s o -l domain
complete -c virt-qemu-sev-validate -s i -l insecure
complete -c virt-qemu-sev-validate -s g -l ignore-config
complete -c virt-qemu-sev-validate -l inject-secret
complete -c virt-qemu-sev-validate -l secret-header
complete -c virt-qemu-sev-validate -l secret-payload

