# virtvboxd
# Autogenerated from man page /usr/share/man/man8/virtvboxd.8.gz
complete -c virtvboxd -s h -l help
complete -c virtvboxd -s d -l daemon
complete -c virtvboxd -s f -l config
complete -c virtvboxd -s p -l pid-file
complete -c virtvboxd -s t -l timeout
complete -c virtvboxd -s v -l verbose
complete -c virtvboxd -l version
complete -c virtvboxd -o rw-r--r--

