# virt-install
# Autogenerated from man page /usr/share/man/man1/virt-install.1.gz
complete -c virt-install -l option -d 'argument, example: virt-install --disk=?'
complete -c virt-install -l connect
complete -c virt-install -s n -l name
complete -c virt-install -l memory
complete -c virt-install -l memorybacking
complete -c virt-install -l arch
complete -c virt-install -l machine
complete -c virt-install -l metadata
complete -c virt-install -l events
complete -c virt-install -l resource
complete -c virt-install -l sysinfo
complete -c virt-install -l xml
complete -c virt-install -l qemu-commandline
complete -c virt-install -o display -d 'Environment variables are specified with \'env\', for example:'
complete -c virt-install -l vcpus
complete -c virt-install -l numatune
complete -c virt-install -l memtune
complete -c virt-install -l blkiotune
complete -c virt-install -l cpu
complete -c virt-install -l cputune
complete -c virt-install -l security -l seclabel
complete -c virt-install -l keywrap
complete -c virt-install -l iothreads
complete -c virt-install -l features
complete -c virt-install -l clock
complete -c virt-install -l pm
complete -c virt-install -l launchSecurity
complete -c virt-install -s c -l cdrom
complete -c virt-install -s l -l location
complete -c virt-install -l extra-args -d 'and using --initrd-inject'
complete -c virt-install -l pxe
complete -c virt-install -l import
complete -c virt-install -l disk -l filesystem
complete -c virt-install -s x
complete -c virt-install -l initrd-inject
complete -c virt-install -l install
complete -c virt-install -l reinstall
complete -c virt-install -l unattended
complete -c virt-install -l cloud-init
complete -c virt-install -l boot
complete -c virt-install -l idmap
complete -c virt-install -l os-variant -l osinfo
complete -c virt-install -o s/--file-size -l nonsparse -l nodisks
complete -c virt-install -s w -l network
complete -c virt-install -l graphics
complete -c virt-install -l video -l channel -d 'none No graphical console will be allocated for the guest'
complete -c virt-install -l vnc -l vncport -l vnclisten -o k/--keymap -l sdl -l nographics
complete -c virt-install -l autoconsole
complete -c virt-install -l noautoconsole -d 'Don\'t automatically try to connect to the guest console.  Same as'
complete -c virt-install -s v -l hvm
complete -c virt-install -s p -l paravirt
complete -c virt-install -l container
complete -c virt-install -l virt-type
complete -c virt-install -l controller
complete -c virt-install -l input
complete -c virt-install -l hostdev -l host-device
complete -c virt-install -l sound
complete -c virt-install -l audio
complete -c virt-install -l watchdog
complete -c virt-install -l serial
complete -c virt-install -l parallel -d 'noted.  Some of the types of character device redirection are:'
complete -c virt-install -l console
complete -c virt-install -l smartcard
complete -c virt-install -l redirdev
complete -c virt-install -l memballoon
complete -c virt-install -l tpm
complete -c virt-install -l rng
complete -c virt-install -l panic
complete -c virt-install -l shmem
complete -c virt-install -l memdev
complete -c virt-install -l vsock
complete -c virt-install -l iommu
complete -c virt-install -s h -l help
complete -c virt-install -l version
complete -c virt-install -l autostart
complete -c virt-install -l transient
complete -c virt-install -l destroy-on-exit
complete -c virt-install -l print-xml
complete -c virt-install -l noreboot
complete -c virt-install -l wait
complete -c virt-install -l dry-run
complete -c virt-install -l check
complete -c virt-install -s q -l quiet
complete -c virt-install -s d -l debug

