# virt-qemu-qmp-proxy
# Autogenerated from man page /usr/share/man/man1/virt-qemu-qmp-proxy.1.gz
complete -c virt-qemu-qmp-proxy -s c
complete -c virt-qemu-qmp-proxy -l connect
complete -c virt-qemu-qmp-proxy -s v -l verbose
complete -c virt-qemu-qmp-proxy -s h -l help

