# virt-login-shell
# Autogenerated from man page /usr/share/man/man1/virt-login-shell.1.gz
complete -c virt-login-shell -s c
complete -c virt-login-shell -s h -l help
complete -c virt-login-shell -s V -l version

