# virtlxcd
# Autogenerated from man page /usr/share/man/man8/virtlxcd.8.gz
complete -c virtlxcd -s h -l help
complete -c virtlxcd -s d -l daemon
complete -c virtlxcd -s f -l config
complete -c virtlxcd -s p -l pid-file
complete -c virtlxcd -s t -l timeout
complete -c virtlxcd -s v -l verbose
complete -c virtlxcd -l version
complete -c virtlxcd -o rw-r--r--

