# warnquota
# Autogenerated from man page /usr/share/man/man8/warnquota.8.gz
complete -c warnquota -s F -l format -d 'Perform setting for specified format (ie'
complete -c warnquota -s q -l quota-tab -d 'Use  quotatab instead of  /etc/quotatab as file with device description strin…'
complete -c warnquota -s c -l config -d 'Use  configfile instead of  /etc/warnquota'
complete -c warnquota -s a -l admins-file -d 'Use  adminsfile instead of  /etc/quotagrpadmins as a file with administrators…'
complete -c warnquota -s u -l user -d 'check whether users are not exceeding quotas (default)'
complete -c warnquota -s g -l group -d 'check whether groups are not exceeding quotas'
complete -c warnquota -s s -l human-readable -d 'Try to report used space, number of used inodes and limits in more appropriat…'
complete -c warnquota -s i -l no-autofs -d 'ignore mountpoints mounted by automounter'
complete -c warnquota -s d -l no-details -d 'do not attach quota report in email.  FILES aquota'

