# xmode2
# Autogenerated from man page /usr/share/man/man1/xmode2.1.gz
complete -c xmode2 -s h -l help -d 'display usage summary'
complete -c xmode2 -s v -l version -d 'display version'
complete -c xmode2 -s d -l device -d 'read from given device'
complete -c xmode2 -s H -l driver -d 'use given driver'
complete -c xmode2 -s m -l mode -d 'enable alternative display mode'
complete -c xmode2 -s r -l raw -d 'access device directly'

